const {requirePermission}=require('./auth');

function registerAdminRoutes(app,pool){
  const adminOnly=(req,res,next)=>{if(req.user?.role_code==='admin')return next();res.status(403).json({error:'Acceso restringido a administradores'});};

  app.get('/api/admin/settings',adminOnly,async(req,res)=>{try{const r=await pool.query('select setting_key,category,label,value,description,updated_at from system_settings order by category,setting_key');res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron consultar las configuraciones'})}});
  app.patch('/api/admin/settings/:key',adminOnly,async(req,res)=>{const value=req.body?.value;if(value===undefined)return res.status(400).json({error:'El valor es obligatorio'});try{const r=await pool.query('update system_settings set value=$1::jsonb,updated_at=now(),updated_by=$2 where setting_key=$3 returning *',[JSON.stringify(value),req.user.id,req.params.key]);if(!r.rowCount)return res.status(404).json({error:'Configuración no encontrada'});res.json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo guardar la configuración'})}});

  app.get('/api/admin/permissions',adminOnly,async(req,res)=>{try{const r=await pool.query(`select p.id,p.code,p.name,p.module,coalesce(json_agg(json_build_object('role_id',rp.role_id,'role_code',r.code)) filter(where r.id is not null),'[]') roles from permissions p left join role_permissions rp on rp.permission_id=p.id left join roles r on r.id=rp.role_id group by p.id order by p.module,p.code`);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron consultar los permisos'})}});
  app.get('/api/admin/roles/:id/permissions',adminOnly,async(req,res)=>{try{const r=await pool.query('select p.id,p.code,p.name,p.module from permissions p join role_permissions rp on rp.permission_id=p.id where rp.role_id=$1 order by p.module,p.code',[req.params.id]);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron consultar los permisos del rol'})}});
  app.put('/api/admin/roles/:id/permissions',adminOnly,async(req,res)=>{const ids=Array.isArray(req.body?.permission_ids)?req.body.permission_ids:[];const client=await pool.connect();try{await client.query('begin');await client.query('delete from role_permissions where role_id=$1',[req.params.id]);for(const id of ids)await client.query('insert into role_permissions(role_id,permission_id) values($1,$2) on conflict do nothing',[req.params.id,id]);await client.query('commit');res.json({ok:true})}catch(e){await client.query('rollback');res.status(400).json({error:'No se pudieron guardar los permisos'})}finally{client.release()}});

  app.patch('/api/admin/companies/:id',adminOnly,async(req,res)=>{const b=req.body||{};const fields=[];const vals=[];const add=(f,v)=>{fields.push(`${f}=$${vals.length+1}`);vals.push(v)};['legal_name','rut','trade_name','email','phone','address','commune','region'].forEach(k=>{if(b[k]!==undefined)add(k,b[k]||null)});if(b.active!==undefined)add('active',!!b.active);if(!fields.length)return res.status(400).json({error:'No hay cambios'});vals.push(req.params.id);try{const r=await pool.query(`update companies set ${fields.join(',')},updated_at=now() where id=$${vals.length} returning *`,vals);if(!r.rowCount)return res.sendStatus(404);res.json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo actualizar la empresa'})}});

  app.get('/api/admin/audit',adminOnly,async(req,res)=>{try{const r=await pool.query(`select a.*,u.name user_name,c.legal_name company_name from audit_logs a left join users u on u.id=a.user_id left join companies c on c.id=a.company_id order by a.created_at desc limit 300`);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo consultar la auditoría'})}});
}
module.exports={registerAdminRoutes};
