const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const CORE_MIGRATION = fs.readFileSync(path.join(__dirname,'migrations','002_core_platform.sql'),'utf8');
const clean = v => typeof v === 'string' ? v.trim() : v;
const body = req => req.body && typeof req.body === 'object' ? req.body : {};

function registerCoreRoutes(app,pool){
 app.get('/api/core/summary',async(req,res)=>{try{const q=await Promise.all([
  pool.query('select count(*)::int n from companies where active=true'),pool.query('select count(*)::int n from users where active=true'),pool.query('select count(*)::int n from clients where active=true'),pool.query("select count(*)::int n from trips where status not in ('Completado','Cancelado')"),pool.query("select count(*)::int n from vehicle_documents where expires_at is not null and expires_at <= current_date + interval '30 days'"),pool.query("select count(*)::int n from driver_documents where expires_at is not null and expires_at <= current_date + interval '30 days'")]);res.json({companies:q[0].rows[0].n,users:q[1].rows[0].n,clients:q[2].rows[0].n,active_trips:q[3].rows[0].n,vehicle_documents_due:q[4].rows[0].n,driver_documents_due:q[5].rows[0].n})}catch(e){res.status(500).json({error:'No se pudo cargar el resumen'})}});
 app.get('/api/companies',async(req,res)=>{try{res.json((await pool.query('select * from companies order by id desc')).rows)}catch(e){res.status(500).json({error:'No se pudieron consultar las empresas'})}});
 app.post('/api/companies',async(req,res)=>{const b=body(req);if(!clean(b.legal_name))return res.status(400).json({error:'La razón social es obligatoria'});try{const r=await pool.query(`insert into companies(legal_name,rut,trade_name,email,phone,address,commune,region) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[clean(b.legal_name),clean(b.rut)||null,clean(b.trade_name)||null,clean(b.email)||null,clean(b.phone)||null,clean(b.address)||null,clean(b.commune)||null,clean(b.region)||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.code==='23505'?'El RUT ya existe':'No se pudo crear la empresa'})}});
 app.get('/api/clients',async(req,res)=>{try{res.json((await pool.query('select * from clients order by id desc')).rows)}catch(e){res.status(500).json({error:'No se pudieron consultar los clientes'})}});
 app.post('/api/clients',async(req,res)=>{const b=body(req);if(!clean(b.name))return res.status(400).json({error:'El nombre del cliente es obligatorio'});try{const r=await pool.query(`insert into clients(company_id,rut,name,contact_name,email,phone,address,commune,region,payment_terms_days) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[b.company_id||null,clean(b.rut)||null,clean(b.name),clean(b.contact_name)||null,clean(b.email)||null,clean(b.phone)||null,clean(b.address)||null,clean(b.commune)||null,clean(b.region)||null,Number(b.payment_terms_days||30)]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo crear el cliente'})}});
 app.get('/api/trips',async(req,res)=>{try{const r=await pool.query(`select t.*,tr.patente,dr.name driver_name,c.name client_name from trips t left join trucks tr on tr.id=t.truck_id left join drivers dr on dr.id=t.driver_id left join clients c on c.id=t.client_id order by t.id desc`);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron consultar los viajes'})}});
 app.post('/api/trips',async(req,res)=>{const b=body(req);if(!clean(b.origin)||!clean(b.destination))return res.status(400).json({error:'Origen y destino son obligatorios'});const n=clean(b.trip_number)||`V-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;try{const r=await pool.query(`insert into trips(company_id,trip_number,truck_id,driver_id,client_id,origin,destination,planned_departure,planned_arrival,status,distance_km,revenue_clp,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning *`,[b.company_id||null,n,b.truck_id||null,b.driver_id||null,b.client_id||null,clean(b.origin),clean(b.destination),b.planned_departure||null,b.planned_arrival||null,b.status||'Planificado',Number(b.distance_km||0),Number(b.revenue_clp||0),clean(b.notes)||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.code==='23505'?'El número de viaje ya existe':'No se pudo crear el viaje'})}});
 app.patch('/api/trips/:id/status',async(req,res)=>{const s=clean(req.body?.status);const ok=['Planificado','Asignado','En carga','En tránsito','Detenido','Llegó a destino','Descargando','Completado','Cancelado'];if(!ok.includes(s))return res.status(400).json({error:'Estado de viaje no válido'});try{const r=await pool.query(`update trips set status=$1,updated_at=now(),actual_departure=case when $1='En tránsito' and actual_departure is null then now() else actual_departure end,actual_arrival=case when $1='Completado' then coalesce(actual_arrival,now()) else actual_arrival end where id=$2 returning *`,[s,req.params.id]);if(!r.rowCount)return res.sendStatus(404);await pool.query('insert into trip_events(trip_id,event_type,notes) values($1,$2,$3)',[req.params.id,s,`Estado cambiado a ${s}`]);res.json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo actualizar el viaje'})}});
 app.get('/api/documents/due',async(req,res)=>{try{const[v,d]=await Promise.all([pool.query(`select vd.*,t.patente from vehicle_documents vd left join trucks t on t.id=vd.truck_id where vd.expires_at is not null and vd.expires_at <= current_date + interval '30 days' order by vd.expires_at`),pool.query(`select dd.*,d.name driver_name from driver_documents dd left join drivers d on d.id=dd.driver_id where dd.expires_at is not null and dd.expires_at <= current_date + interval '30 days' order by dd.expires_at`)]);res.json({vehicles:v.rows,drivers:d.rows})}catch(e){res.status(500).json({error:'No se pudieron consultar vencimientos'})}});
 app.post('/api/vehicle-documents',async(req,res)=>{const b=body(req);if(!b.truck_id||!clean(b.document_type))return res.status(400).json({error:'Vehículo y tipo de documento son obligatorios'});try{const r=await pool.query(`insert into vehicle_documents(truck_id,document_type,document_number,issued_at,expires_at,status,file_url,notes) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.truck_id,clean(b.document_type),clean(b.document_number)||null,b.issued_at||null,b.expires_at||null,b.status||'Vigente',b.file_url||null,clean(b.notes)||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo registrar el documento'})}});
 app.post('/api/driver-documents',async(req,res)=>{const b=body(req);if(!b.driver_id||!clean(b.document_type))return res.status(400).json({error:'Conductor y tipo de documento son obligatorios'});try{const r=await pool.query(`insert into driver_documents(driver_id,document_type,document_number,issued_at,expires_at,status,file_url,notes) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.driver_id,clean(b.document_type),clean(b.document_number)||null,b.issued_at||null,b.expires_at||null,b.status||'Vigente',b.file_url||null,clean(b.notes)||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo registrar el documento'})}});
 app.get('/api/audit',async(req,res)=>{try{res.json((await pool.query('select * from audit_logs order by created_at desc limit 200')).rows)}catch(e){res.status(500).json({error:'No se pudo consultar auditoría'})}});
}
async function initializeCorePlatform(pool){await pool.query(CORE_MIGRATION)}
module.exports={registerCoreRoutes,initializeCorePlatform};