const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const {requirePermission}=require('./auth');
const {writeAudit}=require('./audit');
const CORE_MIGRATION = fs.readFileSync(path.join(__dirname,'migrations','002_core_platform.sql'),'utf8');
const clean = v => typeof v === 'string' ? v.trim() : v;
const body = req => req.body && typeof req.body === 'object' ? req.body : {};
const adminOnly=(req,res,next)=>{if(req.user?.role_code==='admin')return next();res.status(403).json({error:'Acceso restringido a administradores'});};
const companyId=req=>req.user?.company_id||null;
const isAdmin=req=>req.user?.role_code==='admin';
const scoped=(req,alias='')=>{const c=alias?`${alias}.company_id`:'company_id';return isAdmin(req)?{sql:'true',values:[]}:{sql:`${c}=$1`,values:[companyId(req)]};};
async function resourceBelongsToCompany(pool,table,id,cid){if(!id)return true;const allowed={trucks:'company_id',drivers:'company_id',clients:'company_id',routes:'company_id'};const col=allowed[table];if(!col||!cid)return false;const r=await pool.query(`select id from ${table} where id=$1 and ${col}=$2`,[id,cid]);return !!r.rowCount;}
async function companyView(db,id){return (await db.query('select id,legal_name,rut,trade_name,email,phone,address,commune,region,active,created_at,updated_at from companies where id=$1',[id])).rows[0]||null;}

function registerCoreRoutes(app,pool){
 app.get('/api/core/summary',requirePermission('dashboard.read'),async(req,res)=>{
   const s=scoped(req);
   const countSafe=async(name,sql,values)=>{try{return (await pool.query(sql,values)).rows[0]?.n||0}catch(e){console.warn(`Resumen: ${name} no disponible:`,e.message);return 0}};
   const companies=await countSafe('empresas',isAdmin(req)?'select count(*)::int n from companies where active=true':'select count(*)::int n from companies where id=$1 and active=true',isAdmin(req)?[]:[companyId(req)]);
   const users=await countSafe('usuarios',`select count(*)::int n from users where active=true and (${s.sql})`,s.values);
   const clients=await countSafe('clientes',`select count(*)::int n from clients where active=true and (${s.sql})`,s.values);
   const active_trips=await countSafe('viajes',`select count(*)::int n from trips where status not in ('Completado','Cancelado') and (${s.sql})`,s.values);
   let vehicleDocuments=0,driverDocuments=0;
   try{const[v,d]=await Promise.all([
     pool.query(`select count(*)::int n from vehicle_documents vd join trucks t on t.id=vd.truck_id where vd.expires_at is not null and vd.expires_at <= current_date + interval '30 days' and (${scoped(req,'t').sql})`,scoped(req,'t').values),
     pool.query(`select count(*)::int n from driver_documents dd join drivers d on d.id=dd.driver_id where dd.expires_at is not null and dd.expires_at <= current_date + interval '30 days' and (${scoped(req,'d').sql})`,scoped(req,'d').values)
   ]);vehicleDocuments=v.rows[0]?.n||0;driverDocuments=d.rows[0]?.n||0}catch(e){console.warn('Resumen: vencimientos no disponibles:',e.message)}
   res.json({companies,users,clients,active_trips,vehicle_documents_due:vehicleDocuments,driver_documents_due:driverDocuments});
 });
 app.get('/api/companies',adminOnly,async(req,res)=>{try{res.json((await pool.query('select * from companies order by id desc')).rows)}catch(e){res.status(500).json({error:'No se pudieron consultar las empresas'})}});
 app.post('/api/companies',adminOnly,async(req,res)=>{const b=body(req);if(!clean(b.legal_name))return res.status(400).json({error:'La razón social es obligatoria'});const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query(`insert into companies(legal_name,rut,trade_name,email,phone,address,commune,region) values($1,$2,$3,$4,$5,$6,$7,$8) returning id`,[clean(b.legal_name),clean(b.rut)||null,clean(b.trade_name)||null,clean(b.email)||null,clean(b.phone)||null,clean(b.address)||null,clean(b.commune)||null,clean(b.region)||null]);const company=await companyView(client,r.rows[0].id);if(!company)throw new Error('No se pudo obtener la empresa creada');await writeAudit(client,req,{companyId:company.id,action:'create',entity:'company',entityId:company.id,afterData:company});await client.query('COMMIT');res.status(201).json(company)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.code==='23505'?'El RUT ya existe':'No se pudo crear la empresa'})}finally{client.release()}});
 app.get('/api/clients',requirePermission('clients.manage'),async(req,res)=>{const s=scoped(req);try{res.json((await pool.query(`select * from clients where ${s.sql} order by id desc`,s.values)).rows)}catch(e){res.status(500).json({error:'No se pudieron consultar los clientes'})}});
 app.post('/api/clients',requirePermission('clients.manage'),async(req,res)=>{const b=body(req);if(!clean(b.name))return res.status(400).json({error:'El nombre del cliente es obligatorio'});const cid=isAdmin(req)?(b.company_id||companyId(req)):companyId(req);if(!cid)return res.status(400).json({error:'El usuario no tiene empresa asignada'});try{const r=await pool.query(`insert into clients(company_id,rut,name,contact_name,email,phone,address,commune,region,payment_terms_days) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[cid,clean(b.rut)||null,clean(b.name),clean(b.contact_name)||null,clean(b.email)||null,clean(b.phone)||null,clean(b.address)||null,clean(b.commune)||null,clean(b.region)||null,Number(b.payment_terms_days||30)]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo crear el cliente'})}});
 app.get('/api/trips',requirePermission('trips.manage'),async(req,res)=>{const s=scoped(req,'t');try{res.json((await pool.query(`select t.*,tr.patente,dr.name driver_name,c.name client_name from trips t left join trucks tr on tr.id=t.truck_id left join drivers dr on dr.id=t.driver_id left join clients c on c.id=t.client_id where ${s.sql} order by t.id desc`,s.values)).rows)}catch(e){res.status(500).json({error:'No se pudieron consultar los viajes'})}});
 app.post('/api/trips',requirePermission('trips.manage'),async(req,res)=>{const b=body(req);if(!clean(b.origin)||!clean(b.destination))return res.status(400).json({error:'Origen y destino son obligatorios'});const cid=isAdmin(req)?(b.company_id||companyId(req)):companyId(req);if(!cid)return res.status(400).json({error:'El usuario no tiene empresa asignada'});const n=clean(b.trip_number)||`V-${new Date().getFullYear()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;const client=await pool.connect();try{await client.query('BEGIN');for(const [table,id,label] of [['trucks',b.truck_id,'camión'],['drivers',b.driver_id,'conductor'],['clients',b.client_id,'cliente'],['routes',b.route_id,'ruta']]){if(id&&!await resourceBelongsToCompany(client,table,id,cid)){await client.query('ROLLBACK');return res.status(403).json({error:`El ${label} no pertenece a la empresa del viaje`})}}const r=await client.query(`insert into trips(company_id,trip_number,truck_id,driver_id,client_id,route_id,origin,destination,planned_departure,planned_arrival,status,distance_km,revenue_clp,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *`,[cid,n,b.truck_id||null,b.driver_id||null,b.client_id||null,b.route_id||null,clean(b.origin),clean(b.destination),b.planned_departure||null,b.planned_arrival||null,'Planificado',Number(b.distance_km||0),Number(b.revenue_clp||0),clean(b.notes)||null]);await client.query('insert into trip_status_history(trip_id,from_status,to_status,created_by) values($1,$2,$3,$4)',[r.rows[0].id,null,'Planificado',req.user?.id||null]);await writeAudit(client,req,{companyId:cid,action:'create',entity:'trip',entityId:r.rows[0].id,afterData:r.rows[0]});await client.query('COMMIT');res.status(201).json(r.rows[0])}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.code==='23505'?'El número de viaje ya existe':'No se pudo crear el viaje'})}finally{client.release()}});
 app.patch('/api/trips/:id/status',requirePermission('trips.manage'),async(req,res)=>{const s=clean(req.body?.status);const ok=['Planificado','Asignado','En carga','En tránsito','Detenido','Llegó a destino','Descargando','Completado','Cancelado'];if(!ok.includes(s))return res.status(400).json({error:'Estado de viaje no válido'});const client=await pool.connect();try{await client.query('BEGIN');const oldQ=isAdmin(req)?await client.query('select * from trips where id=$1 for update',[req.params.id]):await client.query('select * from trips where id=$1 and company_id=$2 for update',[req.params.id,companyId(req)]);const old=oldQ.rows[0];if(!old){await client.query('ROLLBACK');return res.sendStatus(404)}const r=await client.query(`update trips set status=$1,updated_at=now(),actual_departure=case when $1='En tránsito' and actual_departure is null then now() else actual_departure end,actual_arrival=case when $1='Completado' then coalesce(actual_arrival,now()) else actual_arrival end where id=$2${isAdmin(req)?'':' and company_id=$3'} returning *`,isAdmin(req)?[s,req.params.id]:[s,req.params.id,companyId(req)]);await client.query('insert into trip_status_history(trip_id,from_status,to_status,notes,created_by) values($1,$2,$3,$4,$5)',[req.params.id,old.status,s,clean(req.body?.notes)||null,req.user?.id||null]);await client.query('insert into trip_events(trip_id,event_type,notes,created_by) values($1,$2,$3,$4)',[req.params.id,s,clean(req.body?.notes)||`Estado cambiado a ${s}`,req.user?.id||null]);await writeAudit(client,req,{companyId:old.company_id,action:'status_change',entity:'trip',entityId:req.params.id,beforeData:old,afterData:r.rows[0]});await client.query('COMMIT');res.json(r.rows[0])}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo actualizar el viaje'})}finally{client.release()}});
 app.get('/api/documents/due',requirePermission('documents.manage'),async(req,res)=>{try{const sT=scoped(req,'t'),sD=scoped(req,'d');const[v,d]=await Promise.all([pool.query(`select vd.*,t.patente from vehicle_documents vd left join trucks t on t.id=vd.truck_id where vd.expires_at is not null and vd.expires_at <= current_date + interval '30 days' and (${sT.sql}) order by vd.expires_at`,sT.values),pool.query(`select dd.*,d.name driver_name from driver_documents dd left join drivers d on d.id=dd.driver_id where dd.expires_at is not null and dd.expires_at <= current_date + interval '30 days' and (${sD.sql}) order by dd.expires_at`,sD.values)]);res.json({vehicles:v.rows,drivers:d.rows})}catch(e){res.status(500).json({error:'No se pudieron consultar vencimientos'})}});
 app.post('/api/vehicle-documents',requirePermission('documents.manage'),async(req,res)=>{const b=body(req);if(!b.truck_id||!clean(b.document_type))return res.status(400).json({error:'Vehículo y tipo de documento son obligatorios'});try{const params=isAdmin(req)?[b.truck_id]:[b.truck_id,companyId(req)];const filter=isAdmin(req)?'id=$1':'id=$1 and company_id=$2';const t=await pool.query(`select id from trucks where ${filter}`,params);if(!t.rowCount)return res.status(404).json({error:'Vehículo no encontrado'});const r=await pool.query(`insert into vehicle_documents(truck_id,document_type,document_number,issued_at,expires_at,status,file_url,notes) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.truck_id,clean(b.document_type),clean(b.document_number)||null,b.issued_at||null,b.expires_at||null,b.status||'Vigente',b.file_url||null,b.notes||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo registrar el documento'})}});
 app.post('/api/driver-documents',requirePermission('documents.manage'),async(req,res)=>{const b=body(req);if(!b.driver_id||!clean(b.document_type))return res.status(400).json({error:'Conductor y tipo de documento son obligatorios'});try{const params=isAdmin(req)?[b.driver_id]:[b.driver_id,companyId(req)];const filter=isAdmin(req)?'id=$1':'id=$1 and company_id=$2';const d=await pool.query(`select id from drivers where ${filter}`,params);if(!d.rowCount)return res.status(404).json({error:'Conductor no encontrado'});const r=await pool.query(`insert into driver_documents(driver_id,document_type,document_number,issued_at,expires_at,status,file_url,notes) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.driver_id,clean(b.document_type),clean(b.document_number)||null,b.issued_at||null,b.expires_at||null,b.status||'Vigente',b.file_url||null,b.notes||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo registrar el documento'})}});
 app.get('/api/audit',requirePermission('audit.read'),async(req,res)=>{const s=scoped(req,'a');try{res.json((await pool.query(`select a.*,u.name user_name,c.legal_name company_name from audit_logs a left join users u on u.id=a.user_id left join companies c on c.id=a.company_id where ${s.sql} order by a.created_at desc limit 200`,s.values)).rows)}catch(e){res.status(500).json({error:'No se pudo consultar auditoría'})}});
}
async function initializeCorePlatform(pool){await pool.query(CORE_MIGRATION)}
module.exports={registerCoreRoutes,initializeCorePlatform};
