const {requirePermission}=require('./auth');
const {writeAudit}=require('./audit');
const body=req=>req.body&&typeof req.body==='object'?req.body:{};
const clean=v=>typeof v==='string'?v.trim():v;
const isAdmin=req=>req.user?.role_code==='admin';
const userCompany=req=>req.user?.company_id||null;
const parseDate=v=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()};
const parseNumber=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const parseFuelNumber=v=>{if(typeof v!=='number'&&typeof v!=='string')return null;if(typeof v==='string'&&!v.trim())return null;const n=Number(v);return Number.isFinite(n)?n:null};
const parseFuelDate=v=>{if(v===null||v===undefined||v==='')return null;if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(`${v}T00:00:00.000Z`);return Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==v?false:v};
const scope=(req,alias='t',parameter=1)=>{const c=`${alias}.company_id`;return isAdmin(req)?{sql:'true',values:[]}:{sql:`${c}=$${parameter}`,values:[userCompany(req)]};};
async function fleetCompany(req,pool,id,table){const s=scope(req,'x',2);const r=await pool.query(`select id,company_id from ${table} x where x.id=$1 and ${s.sql}`,[id,...s.values]);return r.rows[0]||null}
function fuelMetrics(rows){
 const records=rows.map(row=>{const odometer=parseNumber(row.odometer_km),previous=parseNumber(row.previous_odometer_km),liters=parseNumber(row.liters),total=parseNumber(row.total_clp);const distance=odometer!==null&&previous!==null&&odometer>previous?odometer-previous:null;return {...row,distance_km:distance,efficiency_km_l:distance!==null&&liters>0?distance/liters:null,cost_per_km:distance!==null&&total!==null?total/distance:null}});
 const groups=new Map();
 for(const row of records){if(!row.truck_id)continue;const key=String(row.truck_id);if(!groups.has(key))groups.set(key,{truck_id:row.truck_id,patente:row.truck_patente||row.truck||null,loads_count:0,total_liters:0,total_cost_clp:0,calculable_distance_km:0,calculable_liters:0,calculable_cost_clp:0});const item=groups.get(key);item.loads_count++;item.total_liters+=Number(row.liters||0);item.total_cost_clp+=Number(row.total_clp||0);if(row.distance_km!==null){item.calculable_distance_km+=row.distance_km;item.calculable_liters+=Number(row.liters||0);item.calculable_cost_clp+=Number(row.total_clp||0)}}
 const summary=[...groups.values()].map(item=>({...item,efficiency_km_l:item.calculable_distance_km>0&&item.calculable_liters>0?item.calculable_distance_km/item.calculable_liters:null,cost_per_km:item.calculable_distance_km>0?item.calculable_cost_clp/item.calculable_distance_km:null}));
 const totals={loads_count:records.length,total_liters:records.reduce((sum,row)=>sum+Number(row.liters||0),0),total_cost_clp:records.reduce((sum,row)=>sum+Number(row.total_clp||0),0),calculable_distance_km:summary.reduce((sum,row)=>sum+row.calculable_distance_km,0),calculable_liters:summary.reduce((sum,row)=>sum+row.calculable_liters,0),calculable_cost_clp:summary.reduce((sum,row)=>sum+row.calculable_cost_clp,0)};
 totals.efficiency_km_l=totals.calculable_distance_km>0&&totals.calculable_liters>0?totals.calculable_distance_km/totals.calculable_liters:null;totals.cost_per_km=totals.calculable_distance_km>0?totals.calculable_cost_clp/totals.calculable_distance_km:null;
 return {records,summary,totals};
}
const MAINTENANCE_TYPES=['Preventiva','Correctiva'];
const MAINTENANCE_STATUSES=['Pendiente','En proceso','Completada','Cancelada'];
const ALERT_SOURCE_TYPES=['maintenance','vehicle_document','driver_document','truck','checklist'];
const ALERT_CONDITION_CODES=['maintenance_due_date','maintenance_overdue_date','maintenance_overdue_odometer','truck_maintenance_status','vehicle_document_due','vehicle_document_expired','driver_document_due','driver_document_expired'];
const has=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
function maintenanceMetrics(rows){
 const records=rows.map(row=>{const odometer=parseFuelNumber(row.odometer_km),previous=parseFuelNumber(row.previous_odometer_km),total=parseFuelNumber(row.cost_clp);const distance=odometer!==null&&previous!==null&&odometer>previous?odometer-previous:null;return {...row,distance_since_previous_km:distance,cost_per_km:distance!==null&&total!==null?total/distance:null}});
 const groups=new Map();
 for(const row of records){if(!row.truck_id)continue;const key=String(row.truck_id);if(!groups.has(key))groups.set(key,{truck_id:row.truck_id,patente:row.truck_patente||row.truck||null,maintenance_count:0,total_cost_clp:0,upcoming_count:0,overdue_count:0});const item=groups.get(key);item.maintenance_count++;item.total_cost_clp+=Number(row.cost_clp||0);if(row.is_upcoming)item.upcoming_count++;if(row.is_overdue)item.overdue_count++}
 return {records,summary:[...groups.values()],totals:{maintenance_count:records.length,total_cost_clp:records.reduce((sum,row)=>sum+Number(row.cost_clp||0),0),upcoming_count:records.filter(row=>row.is_upcoming).length,overdue_count:records.filter(row=>row.is_overdue).length}};
}
function maintenanceInput(b,{partial=false,current={}}={}){
 const read=(key,fallback=null)=>has(b,key)?b[key]:partial?current[key]:fallback;
 const truckId=parseFuelNumber(read('truck_id'));
 const item=clean(read('item'));
 const type=clean(read('maintenance_type'));
 const status=clean(read('status','Pendiente'))||'Pendiente';
 const due=parseFuelDate(read('due'));
 const performed=parseFuelDate(read('performed_at'));
 const nextDue=parseFuelDate(read('next_due_date'));
 const odometer=parseFuelNumber(read('odometer_km'));
 const nextOdometer=parseFuelNumber(read('next_due_odometer_km'));
 const partsCost=parseFuelNumber(read('parts_cost_clp',0));
 const laborCost=parseFuelNumber(read('labor_cost_clp',0));
 if(!Number.isInteger(truckId)||truckId<1)return {error:'truck_id es obligatorio'};
 if(!item)return {error:'servicio es obligatorio'};
 if(!MAINTENANCE_TYPES.includes(type))return {error:'maintenance_type no válido'};
 if(!MAINTENANCE_STATUSES.includes(status))return {error:'status no válido'};
 if(due===false||performed===false||nextDue===false)return {error:'Fecha no válida'};
 if(odometer!==null&&odometer<0)return {error:'odometer_km no válido'};
 if(nextOdometer!==null&&nextOdometer<0)return {error:'next_due_odometer_km no válido'};
 if(!Number.isInteger(partsCost)||partsCost<0||!Number.isInteger(laborCost)||laborCost<0)return {error:'costos no válidos'};
 const costsChanged=has(b,'parts_cost_clp')||has(b,'labor_cost_clp');
 const legacyUnsplit=partial&&Number(current.cost_clp||0)>0&&Number(current.parts_cost_clp||0)===0&&Number(current.labor_cost_clp||0)===0;
 const total=partial&&(!costsChanged||(legacyUnsplit&&partsCost===0&&laborCost===0))?Number(current.cost_clp||0):partsCost+laborCost;
 return {truckId,item,type,status,due,performed,nextDue,odometer,nextOdometer,partsCost,laborCost,total,workshop:clean(read('workshop'))||null,notes:clean(read('notes'))||null,partsDescription:clean(read('parts_description'))||null};
}
const alertKey=item=>`${item.source_type}:${item.source_id}:${item.condition_code}`;
function maintenanceAlertsEnabled(value){return value===undefined||value===null||value===true||value==='true'}
async function registerFleetRoutes(app,pool){
 app.get('/api/fleet/positions',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t');const vals=[...s.values];const where=[s.sql];if(req.query.truck_id){vals.push(Number(req.query.truck_id));where.push(`te.truck_id=$${vals.length}`)}if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const limit=Math.min(Math.max(Number(req.query.limit)||500,1),5000);vals.push(limit);const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at,t.patente,t.status,t.location from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at desc,te.id desc limit $${vals.length}`,vals);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron consultar las posiciones'})}});
 app.get('/api/fleet/trucks/:id/positions',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t',2);const vals=[Number(req.params.id),...s.values];const where=[`te.truck_id=$1`,s.sql];if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at desc,te.id desc limit 1000`,vals);if(!r.rowCount&&isAdmin(req)){const exists=await pool.query('select id from trucks where id=$1',[req.params.id]);if(!exists.rowCount)return res.sendStatus(404)}res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo consultar el historial GPS'})}});
 app.get('/api/fleet/trucks/:id/position',requirePermission('gps.read'),async(req,res)=>{try{const truckId=Number(req.params.id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});const s=scope(req,'t',2);const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where te.truck_id=$1 and ${s.sql} order by te.recorded_at desc,te.id desc limit 1`,[truckId,...s.values]);if(!r.rowCount)return res.sendStatus(404);res.json(r.rows[0])}catch(e){res.status(500).json({error:'No se pudo consultar la posición del camión'})}});
 app.get('/api/fleet/trucks/:id/track',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t',2);const vals=[Number(req.params.id),...s.values];const where=[`te.truck_id=$1`,s.sql];if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at asc,te.id asc limit 10000`,vals);res.json({truck_id:Number(req.params.id),points:r.rows})}catch(e){res.status(500).json({error:'No se pudo construir el recorrido'})}});
 app.post('/api/fleet/positions',requirePermission('fleet.manage'),async(req,res)=>{const b=body(req);const truckId=Number(b.truck_id);const lat=parseNumber(b.lat),lng=parseNumber(b.lng),speed=parseNumber(b.speed_kmh)??0,km=parseNumber(b.km);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id es obligatorio'});if(lat===null||lat<-90||lat>90||lng===null||lng<-180||lng>180)return res.status(400).json({error:'latitud o longitud no válidas'});if(speed<0||(km!==null&&km<0))return res.status(400).json({error:'velocidad o kilometraje no válidos'});const recorded=parseDate(b.recorded_at)||new Date().toISOString();const client=await pool.connect();try{await client.query('BEGIN');const truck=(await client.query(isAdmin(req)?'select id,company_id,km,status from trucks where id=$1 for update':'select id,company_id,km,status from trucks where id=$1 and company_id=$2 for update',isAdmin(req)?[truckId]:[truckId,userCompany(req)])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}let tripId=b.trip_id?Number(b.trip_id):null;if(tripId){const trip=(await client.query('select id,company_id from trips where id=$1',[tripId])).rows[0];if(!trip||trip.company_id!==truck.company_id){await client.query('ROLLBACK');return res.status(403).json({error:'El viaje no pertenece a la empresa del camión'})}}const finalKm=km===null?Number(truck.km||0):km;const telemetry=(await client.query('insert into telemetry(truck_id,trip_id,lat,lng,speed_kmh,km,recorded_at) values($1,$2,$3,$4,$5,$6,$7) returning *',[truckId,tripId,lat,lng,speed,finalKm,recorded])).rows[0];const updated=(await client.query('update trucks set lat=$1,lng=$2,km=$3,location=coalesce($4,location) where id=$5 and company_id=$6 returning *',[lat,lng,finalKm,clean(b.location)||null,truckId,truck.company_id])).rows[0];await client.query('COMMIT');res.status(201).json({position:telemetry,truck:updated})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo registrar la posición GPS'})}finally{client.release()}});
 app.get('/api/fleet/live',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t');const r=await pool.query(`select t.id,t.patente,t.status,t.location,t.lat,t.lng,t.km,coalesce(te.speed_kmh,0) speed_kmh,te.recorded_at,te.trip_id from trucks t left join lateral (select speed_kmh,recorded_at,trip_id from telemetry where truck_id=t.id order by recorded_at desc,id desc limit 1) te on true where ${s.sql} order by t.patente`,s.values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo cargar la posición actual de la flota'})}});

 app.get('/api/fleet/fuel',requirePermission('fuel.manage'),async(req,res)=>{try{const s=scope(req,'f');const values=[...s.values],inner=[s.sql],outer=[];if(req.query.truck_id){const truckId=Number(req.query.truck_id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});values.push(truckId);inner.push(`f.truck_id=$${values.length}`)}if(req.query.from){const from=parseFuelDate(req.query.from);if(!from)return res.status(400).json({error:'Fecha inicial no válida'});values.push(from);outer.push(`q.date >= $${values.length}`)}if(req.query.to){const to=parseFuelDate(req.query.to);if(!to)return res.status(400).json({error:'Fecha final no válida'});values.push(to);outer.push(`q.date <= $${values.length}`)}const query=`select * from (select f.*,t.patente truck_patente,case when f.truck_id is null then null else lag(f.odometer_km) over(partition by f.truck_id order by f.date asc,f.id asc) end previous_odometer_km from fuel f left join trucks t on t.id=f.truck_id and t.company_id=f.company_id where ${inner.join(' and ')}) q${outer.length?` where ${outer.join(' and ')}`:''} order by q.date desc,q.id desc limit 1000`;const r=await pool.query(query,values);const result=fuelMetrics(r.rows);res.json(req.query.include_summary==='true'?result:result.records)}catch(e){res.status(500).json({error:'No se pudo cargar el combustible'})}});
 app.post('/api/fleet/fuel',requirePermission('fuel.manage'),async(req,res)=>{const b=body(req),cid=isAdmin(req)?parseFuelNumber(b.company_id):userCompany(req),truckId=parseFuelNumber(b.truck_id),liters=parseFuelNumber(b.liters),price=parseFuelNumber(b.price_clp),odometer=parseFuelNumber(b.odometer_km),date=parseFuelDate(b.date);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id es obligatorio'});if(liters===null||liters<=0)return res.status(400).json({error:'liters debe ser mayor que cero'});if(price===null||price<=0)return res.status(400).json({error:'price_clp debe ser mayor que cero'});if(odometer===null||odometer<0)return res.status(400).json({error:'odometer_km no válido'});if(date===false)return res.status(400).json({error:'Fecha no válida'});const client=await pool.connect();try{await client.query('BEGIN');const truck=(await client.query('select id,company_id,patente from trucks where id=$1 and company_id=$2 for share',[truckId,cid])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}const created=(await client.query('insert into fuel(company_id,date,truck,truck_id,liters,price_clp,total_clp,station,odometer_km) values($1,coalesce($2,current_date),$3,$4,$5,$6,$5*$6,$7,$8) returning *',[cid,date,truck.patente,truck.id,liters,price,clean(b.station)||null,odometer])).rows[0];const result={...created,truck_patente:truck.patente};await writeAudit(client,req,{companyId:cid,action:'create',entity:'fuel',entityId:created.id,afterData:result});await client.query('COMMIT');res.status(201).json(result)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo registrar el combustible'})}finally{client.release()}});

 app.get('/api/fleet/maintenance',requirePermission('maintenance.manage'),async(req,res)=>{try{const s=scope(req,'m');const values=[...s.values],inner=[s.sql],outer=[];if(req.query.truck_id){const truckId=parseFuelNumber(req.query.truck_id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});values.push(truckId);inner.push(`m.truck_id=$${values.length}`)}if(req.query.status){if(!MAINTENANCE_STATUSES.includes(req.query.status))return res.status(400).json({error:'status no válido'});values.push(req.query.status);outer.push(`q.status=$${values.length}`)}if(req.query.maintenance_type){if(!MAINTENANCE_TYPES.includes(req.query.maintenance_type))return res.status(400).json({error:'maintenance_type no válido'});values.push(req.query.maintenance_type);outer.push(`q.maintenance_type=$${values.length}`)}if(req.query.from){const from=parseFuelDate(req.query.from);if(!from)return res.status(400).json({error:'Fecha inicial no válida'});values.push(from);outer.push(`q.effective_date >= $${values.length}`)}if(req.query.to){const to=parseFuelDate(req.query.to);if(!to)return res.status(400).json({error:'Fecha final no válida'});values.push(to);outer.push(`q.effective_date <= $${values.length}`)}if(req.query.upcoming==='true')outer.push('q.is_upcoming=true');if(req.query.overdue==='true')outer.push('q.is_overdue=true');const query=`select * from (select m.*,coalesce(t.patente,m.truck) truck_patente,coalesce(m.performed_at,m.due,m.next_due_date,m.created_at::date) effective_date,case when m.truck_id is null then null else lag(m.odometer_km) over(partition by m.truck_id order by coalesce(m.performed_at,m.due,m.created_at::date) asc,m.id asc) end previous_odometer_km,(m.status not in ('Completada','Cancelada') and m.next_due_date between current_date and current_date+7) is_upcoming,(m.status not in ('Completada','Cancelada') and ((coalesce(m.next_due_date,m.due) is not null and coalesce(m.next_due_date,m.due)<current_date) or (m.next_due_odometer_km is not null and t.km>=m.next_due_odometer_km))) is_overdue from maintenance m left join trucks t on t.id=m.truck_id and t.company_id=m.company_id where ${inner.join(' and ')}) q${outer.length?` where ${outer.join(' and ')}`:''} order by q.effective_date desc nulls last,q.id desc limit 1000`;const r=await pool.query(query,values);const result=maintenanceMetrics(r.rows);res.json(req.query.include_summary==='true'?result:result.records)}catch(e){res.status(500).json({error:'No se pudieron cargar las mantenciones'})}});
 app.post('/api/fleet/maintenance',requirePermission('maintenance.manage'),async(req,res)=>{const b=body(req),cid=isAdmin(req)?parseFuelNumber(b.company_id):userCompany(req);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});const input=maintenanceInput(b);if(input.error)return res.status(400).json({error:input.error});const client=await pool.connect();try{await client.query('BEGIN');const truck=(await client.query('select id,company_id,patente from trucks where id=$1 and company_id=$2 for share',[input.truckId,cid])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}const created=(await client.query('insert into maintenance(company_id,truck,truck_id,item,due,cost_clp,status,maintenance_type,performed_at,odometer_km,workshop,notes,parts_description,parts_cost_clp,labor_cost_clp,next_due_date,next_due_odometer_km,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,now(),now()) returning *',[cid,truck.patente,truck.id,input.item,input.due,input.total,input.status,input.type,input.performed,input.odometer,input.workshop,input.notes,input.partsDescription,input.partsCost,input.laborCost,input.nextDue,input.nextOdometer])).rows[0];const result={...created,truck_patente:truck.patente};await writeAudit(client,req,{companyId:cid,action:'create',entity:'maintenance',entityId:created.id,afterData:result});await client.query('COMMIT');res.status(201).json(result)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo registrar la mantención'})}finally{client.release()}});
 app.patch('/api/fleet/maintenance/:id',requirePermission('maintenance.manage'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const s=scope(req,'m',2);const before=(await client.query(`select m.*,coalesce(t.patente,m.truck) truck_patente from maintenance m left join trucks t on t.id=m.truck_id and t.company_id=m.company_id where m.id=$1 and ${s.sql} for update of m`,[Number(req.params.id),...s.values])).rows[0];if(!before){await client.query('ROLLBACK');return res.sendStatus(404)}const input=maintenanceInput(body(req),{partial:true,current:before});if(input.error){await client.query('ROLLBACK');return res.status(400).json({error:input.error})}const truck=(await client.query('select id,company_id,patente from trucks where id=$1 and company_id=$2 for share',[input.truckId,before.company_id])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}const after=(await client.query('update maintenance set truck=$1,truck_id=$2,item=$3,due=$4,cost_clp=$5,status=$6,maintenance_type=$7,performed_at=$8,odometer_km=$9,workshop=$10,notes=$11,parts_description=$12,parts_cost_clp=$13,labor_cost_clp=$14,next_due_date=$15,next_due_odometer_km=$16,updated_at=now() where id=$17 returning *',[truck.patente,truck.id,input.item,input.due,input.total,input.status,input.type,input.performed,input.odometer,input.workshop,input.notes,input.partsDescription,input.partsCost,input.laborCost,input.nextDue,input.nextOdometer,Number(req.params.id)])).rows[0];const result={...after,truck_patente:truck.patente};await writeAudit(client,req,{companyId:before.company_id,action:'update',entity:'maintenance',entityId:before.id,beforeData:before,afterData:result});await client.query('COMMIT');res.json(result)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo actualizar la mantención'})}finally{client.release()}});

 app.get('/api/fleet/alerts',requirePermission('dashboard.read'),async(req,res)=>{try{const s=scope(req,'a');const values=[...s.values],inner=[s.sql],outer=[];if(req.query.resolved!==undefined){if(!['true','false'].includes(req.query.resolved))return res.status(400).json({error:'resolved no válido'});values.push(req.query.resolved==='true');inner.push(`a.resolved=$${values.length}`)}if(req.query.level){if(!['warning','critical'].includes(req.query.level))return res.status(400).json({error:'level no válido'});values.push(req.query.level);inner.push(`a.level=$${values.length}`)}if(req.query.source_type){if(!ALERT_SOURCE_TYPES.includes(req.query.source_type))return res.status(400).json({error:'source_type no válido'});values.push(req.query.source_type);inner.push(`a.source_type=$${values.length}`)}if(req.query.condition_code){values.push(clean(req.query.condition_code));inner.push(`a.condition_code=$${values.length}`)}if(req.query.from){const from=parseFuelDate(req.query.from);if(!from)return res.status(400).json({error:'Fecha inicial no válida'});values.push(from);inner.push(`a.created_at::date >= $${values.length}`)}if(req.query.to){const to=parseFuelDate(req.query.to);if(!to)return res.status(400).json({error:'Fecha final no válida'});values.push(to);inner.push(`a.created_at::date <= $${values.length}`)}if(req.query.truck_id){const truckId=parseFuelNumber(req.query.truck_id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});values.push(truckId);outer.push(`q.truck_id=$${values.length}`)}const query=`select * from (select a.*,case when a.source_type='truck' then a.source_id when a.source_type='maintenance' then m.truck_id when a.source_type='vehicle_document' then vd.truck_id when a.source_type='checklist' then vc.truck_id else null end truck_id,coalesce(st.patente,mt.patente,vt.patente,ct.patente) truck_patente,dd.name driver_name,coalesce(vd.document_type,ddoc.document_type) document_type,vc.trip_id checklist_trip_id from alerts a left join maintenance m on a.source_type='maintenance' and m.id=a.source_id left join trucks mt on mt.id=m.truck_id left join trucks st on a.source_type='truck' and st.id=a.source_id left join vehicle_documents vd on a.source_type='vehicle_document' and vd.id=a.source_id left join trucks vt on vt.id=vd.truck_id left join driver_documents ddoc on a.source_type='driver_document' and ddoc.id=a.source_id left join drivers dd on dd.id=ddoc.driver_id left join vehicle_checklists vc on a.source_type='checklist' and vc.id=a.source_id left join trucks ct on ct.id=vc.truck_id where ${inner.join(' and ')}) q${outer.length?` where ${outer.join(' and ')}`:''} order by q.resolved asc,q.created_at desc,q.id desc limit 500`;const r=await pool.query(query,values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron cargar las alertas'})}});
 app.post('/api/fleet/alerts/:id/resolve',requirePermission('fleet.manage'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const s=scope(req,'a',2);const current=(await client.query(`select * from alerts a where a.id=$1 and ${s.sql} for update`,[req.params.id,...s.values])).rows[0];if(!current){await client.query('ROLLBACK');return res.sendStatus(404)}const note=clean(req.body?.resolution_note)||'Resolución manual';if(current.source_type==='checklist'&&!clean(req.body?.resolution_note)){await client.query('ROLLBACK');return res.status(400).json({error:'resolution_note es obligatorio'})}const resolved=(await client.query('update alerts set resolved=true,resolved_at=coalesce(resolved_at,now()),resolved_by=$2,resolution_note=$3 where id=$1 returning *',[current.id,req.user.id,note])).rows[0];if(current.source_type==='checklist')await writeAudit(client,req,{companyId:current.company_id,action:'resolve',entity:'alert',entityId:current.id,beforeData:current,afterData:resolved});await client.query('COMMIT');res.json(resolved)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo resolver la alerta'})}finally{client.release()}});
 app.post('/api/fleet/alerts/generate',requirePermission('fleet.manage'),async(req,res)=>{const cid=isAdmin(req)?parseFuelNumber(req.body?.company_id):userCompany(req);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});const client=await pool.connect();try{await client.query('BEGIN');const candidates=[];const setting=(await client.query("select value from system_settings where setting_key='notifications.maintenance_alerts'")).rows[0];if(maintenanceAlertsEnabled(setting?.value)){const maintenance=(await client.query("select m.id,m.item,m.next_due_date,m.next_due_date<current_date overdue_date,m.next_due_odometer_km,coalesce(t.patente,m.truck) patente,t.km from maintenance m left join trucks t on t.id=m.truck_id and t.company_id=m.company_id where m.company_id=$1 and m.status not in ('Completada','Cancelada') and ((m.next_due_date is not null and m.next_due_date<=current_date+7) or (m.next_due_odometer_km is not null and t.km>=m.next_due_odometer_km))",[cid])).rows;for(const m of maintenance){if(m.next_due_date){const overdue=m.overdue_date===true;candidates.push({source_type:'maintenance',source_id:m.id,condition_code:overdue?'maintenance_overdue_date':'maintenance_due_date',level:overdue?'critical':'warning',title:overdue?'Mantención vencida':'Mantención próxima',text:`${m.item||'Mantención'} · ${m.patente||'Camión sin resolver'} · ${String(m.next_due_date).slice(0,10)}`})}if(m.next_due_odometer_km!==null&&m.next_due_odometer_km!==undefined&&Number(m.km)>=Number(m.next_due_odometer_km))candidates.push({source_type:'maintenance',source_id:m.id,condition_code:'maintenance_overdue_odometer',level:'critical',title:'Mantención vencida por kilometraje',text:`${m.item||'Mantención'} · ${m.patente||'Camión sin resolver'} · ${m.next_due_odometer_km} km`})}}
 const trucks=(await client.query("select id,patente from trucks where company_id=$1 and status='Mantención'",[cid])).rows;for(const t of trucks)candidates.push({source_type:'truck',source_id:t.id,condition_code:'truck_maintenance_status',level:'warning',title:'Camión en mantención',text:`El camión ${t.patente} requiere atención.`});
 const vehicleDocuments=(await client.query("select vd.id,vd.document_type,vd.expires_at,vd.expires_at<current_date expired,t.patente from vehicle_documents vd join trucks t on t.id=vd.truck_id where t.company_id=$1 and vd.expires_at is not null and vd.expires_at<=current_date+30",[cid])).rows;for(const d of vehicleDocuments){const expired=d.expired===true;candidates.push({source_type:'vehicle_document',source_id:d.id,condition_code:expired?'vehicle_document_expired':'vehicle_document_due',level:expired?'critical':'warning',title:expired?'Documento de vehículo vencido':'Documento de vehículo próximo',text:`${d.document_type} · ${d.patente} · ${String(d.expires_at).slice(0,10)}`})}
 const driverDocuments=(await client.query("select dd.id,dd.document_type,dd.expires_at,dd.expires_at<current_date expired,d.name driver_name from driver_documents dd join drivers d on d.id=dd.driver_id where d.company_id=$1 and dd.expires_at is not null and dd.expires_at<=current_date+30",[cid])).rows;for(const d of driverDocuments){const expired=d.expired===true;candidates.push({source_type:'driver_document',source_id:d.id,condition_code:expired?'driver_document_expired':'driver_document_due',level:expired?'critical':'warning',title:expired?'Documento de conductor vencido':'Documento de conductor próximo',text:`${d.document_type} · ${d.driver_name} · ${String(d.expires_at).slice(0,10)}`})}
 const created=[];for(const alert of candidates){const r=await client.query("insert into alerts(company_id,level,title,text,resolved,created_at,source_type,source_id,condition_code) values($1,$2,$3,$4,false,now(),$5,$6,$7) on conflict (company_id,source_type,source_id,condition_code) where resolved=false and source_type is not null and source_id is not null and condition_code is not null do nothing returning *",[cid,alert.level,alert.title,alert.text,alert.source_type,alert.source_id,alert.condition_code]);if(r.rowCount)created.push(r.rows[0])}
 const active=(await client.query('select id,source_type,source_id,condition_code from alerts where company_id=$1 and resolved=false and source_type is not null and source_id is not null and condition_code=any($2::text[]) for update',[cid,ALERT_CONDITION_CODES])).rows;const currentKeys=new Set(candidates.map(alertKey));const resolved=[];for(const alert of active){if(!currentKeys.has(alertKey(alert))){const r=await client.query('update alerts set resolved=true,resolved_at=now() where id=$1 returning *',[alert.id]);if(r.rowCount)resolved.push(r.rows[0])}}
 await client.query('COMMIT');res.json({created:created.length,resolved:resolved.length,alerts:created})}catch(e){await client.query('ROLLBACK');res.status(500).json({error:'No se pudieron generar las alertas'})}finally{client.release()}});
}
module.exports={registerFleetRoutes};
