const {requirePermission}=require('./auth');
const body=req=>req.body&&typeof req.body==='object'?req.body:{};
const clean=v=>typeof v==='string'?v.trim():v;
const isAdmin=req=>req.user?.role_code==='admin';
const userCompany=req=>req.user?.company_id||null;
const parseDate=v=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()};
const parseNumber=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const scope=(req,alias='t',parameter=1)=>{const c=`${alias}.company_id`;return isAdmin(req)?{sql:'true',values:[]}:{sql:`${c}=$${parameter}`,values:[userCompany(req)]};};
async function fleetCompany(req,pool,id,table){const s=scope(req,'x',2);const r=await pool.query(`select id,company_id from ${table} x where x.id=$1 and ${s.sql}`,[id,...s.values]);return r.rows[0]||null}
async function registerFleetRoutes(app,pool){
 app.get('/api/fleet/positions',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t');const vals=[...s.values];const where=[s.sql];if(req.query.truck_id){vals.push(Number(req.query.truck_id));where.push(`te.truck_id=$${vals.length}`)}if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const limit=Math.min(Math.max(Number(req.query.limit)||500,1),5000);vals.push(limit);const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at,t.patente,t.status,t.location from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at desc limit $${vals.length}`,vals);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron consultar las posiciones'})}});
 app.get('/api/fleet/trucks/:id/positions',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t',2);const vals=[Number(req.params.id),...s.values];const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where te.truck_id=$1 and ${s.sql} order by te.recorded_at desc limit 1000`,vals);if(!r.rowCount&&isAdmin(req)){const exists=await pool.query('select id from trucks where id=$1',[req.params.id]);if(!exists.rowCount)return res.sendStatus(404)}res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo consultar el historial GPS'})}});
 app.get('/api/fleet/trucks/:id/position',requirePermission('gps.read'),async(req,res)=>{try{const truckId=Number(req.params.id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});const s=scope(req,'t',2);const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where te.truck_id=$1 and ${s.sql} order by te.recorded_at desc,te.id desc limit 1`,[truckId,...s.values]);if(!r.rowCount)return res.sendStatus(404);res.json(r.rows[0])}catch(e){res.status(500).json({error:'No se pudo consultar la posición del camión'})}});
 app.get('/api/fleet/trucks/:id/track',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t',2);const vals=[Number(req.params.id),...s.values];const where=[`te.truck_id=$1`,s.sql];if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at asc limit 10000`,vals);res.json({truck_id:Number(req.params.id),points:r.rows})}catch(e){res.status(500).json({error:'No se pudo construir el recorrido'})}});
 app.post('/api/fleet/positions',requirePermission('fleet.manage'),async(req,res)=>{const b=body(req);const truckId=Number(b.truck_id);const lat=parseNumber(b.lat),lng=parseNumber(b.lng),speed=parseNumber(b.speed_kmh)??0,km=parseNumber(b.km);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id es obligatorio'});if(lat===null||lat<-90||lat>90||lng===null||lng<-180||lng>180)return res.status(400).json({error:'latitud o longitud no válidas'});if(speed<0||(km!==null&&km<0))return res.status(400).json({error:'velocidad o kilometraje no válidos'});const recorded=parseDate(b.recorded_at)||new Date().toISOString();const client=await pool.connect();try{await client.query('BEGIN');const truck=(await client.query(isAdmin(req)?'select id,company_id,km,status from trucks where id=$1 for update':'select id,company_id,km,status from trucks where id=$1 and company_id=$2 for update',isAdmin(req)?[truckId]:[truckId,userCompany(req)])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}let tripId=b.trip_id?Number(b.trip_id):null;if(tripId){const trip=(await client.query('select id,company_id from trips where id=$1',[tripId])).rows[0];if(!trip||trip.company_id!==truck.company_id){await client.query('ROLLBACK');return res.status(403).json({error:'El viaje no pertenece a la empresa del camión'})}}const finalKm=km===null?Number(truck.km||0):km;const telemetry=(await client.query('insert into telemetry(truck_id,trip_id,lat,lng,speed_kmh,km,recorded_at) values($1,$2,$3,$4,$5,$6,$7) returning *',[truckId,tripId,lat,lng,speed,finalKm,recorded])).rows[0];const updated=(await client.query('update trucks set lat=$1,lng=$2,km=$3,location=coalesce($4,location) where id=$5 and company_id=$6 returning *',[lat,lng,finalKm,clean(b.location)||null,truckId,truck.company_id])).rows[0];await client.query('COMMIT');res.status(201).json({position:telemetry,truck:updated})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo registrar la posición GPS'})}finally{client.release()}});
 app.get('/api/fleet/live',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t');const r=await pool.query(`select t.id,t.patente,t.status,t.location,t.lat,t.lng,t.km,coalesce(te.speed_kmh,0) speed_kmh,te.recorded_at,te.trip_id from trucks t left join lateral (select speed_kmh,recorded_at,trip_id from telemetry where truck_id=t.id order by recorded_at desc limit 1) te on true where ${s.sql} order by t.patente`,s.values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo cargar la posición actual de la flota'})}});

 app.get('/api/fleet/fuel',requirePermission('fuel.manage'),async(req,res)=>{try{const s=scope(req,'f');const r=await pool.query(`select f.* from fuel f where ${s.sql} order by f.date desc,f.id desc limit 1000`,s.values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo cargar el combustible'})}});
 app.post('/api/fleet/fuel',requirePermission('fuel.manage'),async(req,res)=>{const b=body(req),cid=isAdmin(req)?b.company_id:userCompany(req),truck=clean(b.truck);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});if(!truck||parseNumber(b.liters)===null||parseNumber(b.price_clp)===null)return res.status(400).json({error:'camión, litros y precio son obligatorios'});const value=String(truck);const q=/^\d+$/.test(value)?'select id from trucks where id=$1 and company_id=$2':'select id from trucks where patente=$1 and company_id=$2';if(!(await pool.query(q,[value,cid])).rowCount)return res.status(403).json({error:'El camión no pertenece a la empresa'});try{const liters=parseNumber(b.liters),price=parseNumber(b.price_clp);const r=await pool.query('insert into fuel(company_id,date,truck,liters,price_clp,total_clp,station) values($1,$2,$3,$4,$5,$4*$5,$6) returning *',[cid,b.date||null,truck,liters,price,clean(b.station)||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo registrar el combustible'})}});

 app.get('/api/fleet/maintenance',requirePermission('maintenance.manage'),async(req,res)=>{try{const s=scope(req,'m');const r=await pool.query(`select m.* from maintenance m where ${s.sql} order by m.due nulls last,m.id desc limit 1000`,s.values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron cargar las mantenciones'})}});
 app.post('/api/fleet/maintenance',requirePermission('maintenance.manage'),async(req,res)=>{const b=body(req),cid=isAdmin(req)?b.company_id:userCompany(req),truck=clean(b.truck);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});if(!truck||!clean(b.item))return res.status(400).json({error:'camión y servicio son obligatorios'});const value=String(truck);const q=/^\d+$/.test(value)?'select id from trucks where id=$1 and company_id=$2':'select id from trucks where patente=$1 and company_id=$2';if(!(await pool.query(q,[value,cid])).rowCount)return res.status(403).json({error:'El camión no pertenece a la empresa'});try{const r=await pool.query('insert into maintenance(company_id,truck,item,due,cost_clp,status) values($1,$2,$3,$4,$5,$6) returning *',[cid,truck,clean(b.item),b.due||null,Number(b.cost_clp||0),clean(b.status)||'Pendiente']);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo registrar la mantención'})}});

 app.get('/api/fleet/alerts',requirePermission('dashboard.read'),async(req,res)=>{try{const s=scope(req,'a');const r=await pool.query(`select a.* from alerts a where ${s.sql} order by a.resolved asc,a.created_at desc limit 500`,s.values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron cargar las alertas'})}});
 app.post('/api/fleet/alerts/:id/resolve',requirePermission('fleet.manage'),async(req,res)=>{try{const s=scope(req,'a',2);const r=await pool.query(`update alerts set resolved=true where id=$1 and ${s.sql} returning *`,[req.params.id,...s.values]);if(!r.rowCount)return res.sendStatus(404);res.json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo resolver la alerta'})}});
 app.post('/api/fleet/alerts/generate',requirePermission('fleet.manage'),async(req,res)=>{try{const cid=isAdmin(req)?req.body?.company_id:userCompany(req);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});const created=[];const exp=await pool.query("select id,company_id,patente,status,location from trucks where company_id=$1 and status='Mantención'",[cid]);for(const t of exp.rows){const r=await pool.query("insert into alerts(company_id,level,title,text,resolved,created_at) select $1,'warning','Camión en mantención',$2,false,now() where not exists(select 1 from alerts where company_id=$1 and title='Camión en mantención' and text=$2 and resolved=false) returning *",[cid,`El camión ${t.patente} figura en Mantención.`]);if(r.rowCount)created.push(r.rows[0])}const due=await pool.query("select id,truck,item,due from maintenance where company_id=$1 and due is not null and due<=current_date+interval '7 days' and status<>'Completada'",[cid]);for(const m of due.rows){const r=await pool.query("insert into alerts(company_id,level,title,text,resolved,created_at) select $1,case when due<current_date then 'critical' else 'warning' end,'Mantención próxima o vencida',$2,false,now() where not exists(select 1 from alerts where company_id=$1 and title='Mantención próxima o vencida' and text=$2 and resolved=false) returning *",[cid,`Mantención ${m.item||''} del camión ${m.truck||''}: ${m.due}.`]);if(r.rowCount)created.push(r.rows[0])}res.json({created:created.length,alerts:created})}catch(e){res.status(500).json({error:'No se pudieron generar las alertas'})}});
}
module.exports={registerFleetRoutes};
