const {requirePermission}=require('./auth');
const {writeAudit}=require('./audit');
const body=req=>req.body&&typeof req.body==='object'?req.body:{};
const clean=v=>typeof v==='string'?v.trim():v;
const isAdmin=req=>req.user?.role_code==='admin';
const userCompany=req=>req.user?.company_id||null;
const parseDate=v=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()};
const parseNumber=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const parseFuelNumber=v=>{if(typeof v!=='number'&&typeof v!=='string')return null;if(typeof v==='string'&&!v.trim())return null;const n=Number(v);return Number.isFinite(n)?n:null};
const parseFuelDate=v=>{if(v===null||v===undefined||v==='')return null;if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(`${v}T00:00:00.000Z`);return Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==v?false:v};
const scope=(req,alias='t',parameter=1)=>{const c=`${alias}.company_id`;return isAdmin(req)?{sql:'true',values:[]}:{sql:`${c}=$${parameter}`,values:[userCompany(req)]};};
async function fleetCompany(req,pool,id,table){const s=scope(req,'x',2);const r=await pool.query(`select id,company_id from ${table} x where x.id=$1 and ${s.sql}`,[id,...s.values]);return r.rows[0]||null}
function fuelMetrics(rows){
 const records=rows.map(row=>{const odometer=parseNumber(row.odometer_km),previous=parseNumber(row.previous_odometer_km),liters=parseNumber(row.liters),total=parseNumber(row.total_clp);const distance=odometer!==null&&previous!==null&&odometer>previous?odometer-previous:null;return {...row,distance_km:distance,efficiency_km_l:distance!==null&&liters>0?distance/liters:null,cost_per_km:distance!==null&&total!==null?total/distance:null}});
 const groups=new Map();
 for(const row of records){if(!row.truck_id)continue;const key=String(row.truck_id);if(!groups.has(key))groups.set(key,{truck_id:row.truck_id,patente:row.truck_patente||row.truck||null,loads_count:0,total_liters:0,total_cost_clp:0,calculable_distance_km:0,calculable_liters:0,calculable_cost_clp:0});const item=groups.get(key);item.loads_count++;item.total_liters+=Number(row.liters||0);item.total_cost_clp+=Number(row.total_clp||0);if(row.distance_km!==null){item.calculable_distance_km+=row.distance_km;item.calculable_liters+=Number(row.liters||0);item.calculable_cost_clp+=Number(row.total_clp||0)}}
 const summary=[...groups.values()].map(item=>({...item,efficiency_km_l:item.calculable_distance_km>0&&item.calculable_liters>0?item.calculable_distance_km/item.calculable_liters:null,cost_per_km:item.calculable_distance_km>0?item.calculable_cost_clp/item.calculable_distance_km:null}));
 const totals={loads_count:records.length,total_liters:records.reduce((sum,row)=>sum+Number(row.liters||0),0),total_cost_clp:records.reduce((sum,row)=>sum+Number(row.total_clp||0),0),calculable_distance_km:summary.reduce((sum,row)=>sum+row.calculable_distance_km,0),calculable_liters:summary.reduce((sum,row)=>sum+row.calculable_liters,0),calculable_cost_clp:summary.reduce((sum,row)=>sum+row.calculable_cost_clp,0)};
 totals.efficiency_km_l=totals.calculable_distance_km>0&&totals.calculable_liters>0?totals.calculable_distance_km/totals.calculable_liters:null;totals.cost_per_km=totals.calculable_distance_km>0?totals.calculable_cost_clp/totals.calculable_distance_km:null;
 return {records,summary,totals};
}
const MAINTENANCE_TYPES=['Preventiva','Correctiva'];
const MAINTENANCE_STATUSES=['Pendiente','En proceso','Completada','Cancelada'];
const has=(value,key)=>Object.prototype.hasOwnProperty.call(value,key);
function maintenanceMetrics(rows){
 const records=rows.map(row=>{const odometer=parseFuelNumber(row.odometer_km),previous=parseFuelNumber(row.previous_odometer_km),total=parseFuelNumber(row.cost_clp);const distance=odometer!==null&&previous!==null&&odometer>previous?odometer-previous:null;return {...row,distance_since_previous_km:distance,cost_per_km:distance!==null&&total!==null?total/distance:null}});
 const groups=new Map();
 for(const row of records){if(!row.truck_id)continue;const key=String(row.truck_id);if(!groups.has(key))groups.set(key,{truck_id:row.truck_id,patente:row.truck_patente||row.truck||null,maintenance_count:0,total_cost_clp:0,upcoming_count:0,overdue_count:0});const item=groups.get(key);item.maintenance_count++;item.total_cost_clp+=Number(row.cost_clp||0);if(row.is_upcoming)item.upcoming_count++;if(row.is_overdue)item.overdue_count++}
 return {records,summary:[...groups.values()],totals:{maintenance_count:records.length,total_cost_clp:records.reduce((sum,row)=>sum+Number(row.cost_clp||0),0),upcoming_count:records.filter(row=>row.is_upcoming).length,overdue_count:records.filter(row=>row.is_overdue).length}};
}
function maintenanceInput(b,{partial=false,current={}}={}){
 const read=(key,fallback=null)=>has(b,key)?b[key]:partial?current[key]:fallback;
 const truckId=parseFuelNumber(read('truck_id'));
 const item=clean(read('item'));
 const type=clean(read('maintenance_type'));
 const status=clean(read('status','Pendiente'))||'Pendiente';
 const due=parseFuelDate(read('due'));
 const performed=parseFuelDate(read('performed_at'));
 const nextDue=parseFuelDate(read('next_due_date'));
 const odometer=parseFuelNumber(read('odometer_km'));
 const nextOdometer=parseFuelNumber(read('next_due_odometer_km'));
 const partsCost=parseFuelNumber(read('parts_cost_clp',0));
 const laborCost=parseFuelNumber(read('labor_cost_clp',0));
 if(!Number.isInteger(truckId)||truckId<1)return {error:'truck_id es obligatorio'};
 if(!item)return {error:'servicio es obligatorio'};
 if(!MAINTENANCE_TYPES.includes(type))return {error:'maintenance_type no válido'};
 if(!MAINTENANCE_STATUSES.includes(status))return {error:'status no válido'};
 if(due===false||performed===false||nextDue===false)return {error:'Fecha no válida'};
 if(odometer!==null&&odometer<0)return {error:'odometer_km no válido'};
 if(nextOdometer!==null&&nextOdometer<0)return {error:'next_due_odometer_km no válido'};
 if(!Number.isInteger(partsCost)||partsCost<0||!Number.isInteger(laborCost)||laborCost<0)return {error:'costos no válidos'};
 const costsChanged=has(b,'parts_cost_clp')||has(b,'labor_cost_clp');
 const legacyUnsplit=partial&&Number(current.cost_clp||0)>0&&Number(current.parts_cost_clp||0)===0&&Number(current.labor_cost_clp||0)===0;
 const total=partial&&(!costsChanged||(legacyUnsplit&&partsCost===0&&laborCost===0))?Number(current.cost_clp||0):partsCost+laborCost;
 return {truckId,item,type,status,due,performed,nextDue,odometer,nextOdometer,partsCost,laborCost,total,workshop:clean(read('workshop'))||null,notes:clean(read('notes'))||null,partsDescription:clean(read('parts_description'))||null};
}
async function registerFleetRoutes(app,pool){
 app.get('/api/fleet/positions',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t');const vals=[...s.values];const where=[s.sql];if(req.query.truck_id){vals.push(Number(req.query.truck_id));where.push(`te.truck_id=$${vals.length}`)}if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const limit=Math.min(Math.max(Number(req.query.limit)||500,1),5000);vals.push(limit);const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at,t.patente,t.status,t.location from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at desc,te.id desc limit $${vals.length}`,vals);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron consultar las posiciones'})}});
 app.get('/api/fleet/trucks/:id/positions',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t',2);const vals=[Number(req.params.id),...s.values];const where=[`te.truck_id=$1`,s.sql];if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at desc,te.id desc limit 1000`,vals);if(!r.rowCount&&isAdmin(req)){const exists=await pool.query('select id from trucks where id=$1',[req.params.id]);if(!exists.rowCount)return res.sendStatus(404)}res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo consultar el historial GPS'})}});
 app.get('/api/fleet/trucks/:id/position',requirePermission('gps.read'),async(req,res)=>{try{const truckId=Number(req.params.id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});const s=scope(req,'t',2);const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where te.truck_id=$1 and ${s.sql} order by te.recorded_at desc,te.id desc limit 1`,[truckId,...s.values]);if(!r.rowCount)return res.sendStatus(404);res.json(r.rows[0])}catch(e){res.status(500).json({error:'No se pudo consultar la posición del camión'})}});
 app.get('/api/fleet/trucks/:id/track',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t',2);const vals=[Number(req.params.id),...s.values];const where=[`te.truck_id=$1`,s.sql];if(req.query.from){const d=parseDate(req.query.from);if(!d)return res.status(400).json({error:'Fecha inicial no válida'});vals.push(d);where.push(`te.recorded_at >= $${vals.length}`)}if(req.query.to){const d=parseDate(req.query.to);if(!d)return res.status(400).json({error:'Fecha final no válida'});vals.push(d);where.push(`te.recorded_at <= $${vals.length}`)}const r=await pool.query(`select te.id,te.truck_id,te.trip_id,te.lat,te.lng,te.speed_kmh,te.km,te.recorded_at from telemetry te join trucks t on t.id=te.truck_id where ${where.join(' and ')} order by te.recorded_at asc,te.id asc limit 10000`,vals);res.json({truck_id:Number(req.params.id),points:r.rows})}catch(e){res.status(500).json({error:'No se pudo construir el recorrido'})}});
 app.post('/api/fleet/positions',requirePermission('fleet.manage'),async(req,res)=>{const b=body(req);const truckId=Number(b.truck_id);const lat=parseNumber(b.lat),lng=parseNumber(b.lng),speed=parseNumber(b.speed_kmh)??0,km=parseNumber(b.km);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id es obligatorio'});if(lat===null||lat<-90||lat>90||lng===null||lng<-180||lng>180)return res.status(400).json({error:'latitud o longitud no válidas'});if(speed<0||(km!==null&&km<0))return res.status(400).json({error:'velocidad o kilometraje no válidos'});const recorded=parseDate(b.recorded_at)||new Date().toISOString();const client=await pool.connect();try{await client.query('BEGIN');const truck=(await client.query(isAdmin(req)?'select id,company_id,km,status from trucks where id=$1 for update':'select id,company_id,km,status from trucks where id=$1 and company_id=$2 for update',isAdmin(req)?[truckId]:[truckId,userCompany(req)])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}let tripId=b.trip_id?Number(b.trip_id):null;if(tripId){const trip=(await client.query('select id,company_id from trips where id=$1',[tripId])).rows[0];if(!trip||trip.company_id!==truck.company_id){await client.query('ROLLBACK');return res.status(403).json({error:'El viaje no pertenece a la empresa del camión'})}}const finalKm=km===null?Number(truck.km||0):km;const telemetry=(await client.query('insert into telemetry(truck_id,trip_id,lat,lng,speed_kmh,km,recorded_at) values($1,$2,$3,$4,$5,$6,$7) returning *',[truckId,tripId,lat,lng,speed,finalKm,recorded])).rows[0];const updated=(await client.query('update trucks set lat=$1,lng=$2,km=$3,location=coalesce($4,location) where id=$5 and company_id=$6 returning *',[lat,lng,finalKm,clean(b.location)||null,truckId,truck.company_id])).rows[0];await client.query('COMMIT');res.status(201).json({position:telemetry,truck:updated})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo registrar la posición GPS'})}finally{client.release()}});
 app.get('/api/fleet/live',requirePermission('gps.read'),async(req,res)=>{try{const s=scope(req,'t');const r=await pool.query(`select t.id,t.patente,t.status,t.location,t.lat,t.lng,t.km,coalesce(te.speed_kmh,0) speed_kmh,te.recorded_at,te.trip_id from trucks t left join lateral (select speed_kmh,recorded_at,trip_id from telemetry where truck_id=t.id order by recorded_at desc,id desc limit 1) te on true where ${s.sql} order by t.patente`,s.values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudo cargar la posición actual de la flota'})}});

 app.get('/api/fleet/fuel',requirePermission('fuel.manage'),async(req,res)=>{try{const s=scope(req,'f');const values=[...s.values],inner=[s.sql],outer=[];if(req.query.truck_id){const truckId=Number(req.query.truck_id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});values.push(truckId);inner.push(`f.truck_id=$${values.length}`)}if(req.query.from){const from=parseFuelDate(req.query.from);if(!from)return res.status(400).json({error:'Fecha inicial no válida'});values.push(from);outer.push(`q.date >= $${values.length}`)}if(req.query.to){const to=parseFuelDate(req.query.to);if(!to)return res.status(400).json({error:'Fecha final no válida'});values.push(to);outer.push(`q.date <= $${values.length}`)}const query=`select * from (select f.*,t.patente truck_patente,case when f.truck_id is null then null else lag(f.odometer_km) over(partition by f.truck_id order by f.date asc,f.id asc) end previous_odometer_km from fuel f left join trucks t on t.id=f.truck_id and t.company_id=f.company_id where ${inner.join(' and ')}) q${outer.length?` where ${outer.join(' and ')}`:''} order by q.date desc,q.id desc limit 1000`;const r=await pool.query(query,values);const result=fuelMetrics(r.rows);res.json(req.query.include_summary==='true'?result:result.records)}catch(e){res.status(500).json({error:'No se pudo cargar el combustible'})}});
 app.post('/api/fleet/fuel',requirePermission('fuel.manage'),async(req,res)=>{const b=body(req),cid=isAdmin(req)?parseFuelNumber(b.company_id):userCompany(req),truckId=parseFuelNumber(b.truck_id),liters=parseFuelNumber(b.liters),price=parseFuelNumber(b.price_clp),odometer=parseFuelNumber(b.odometer_km),date=parseFuelDate(b.date);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id es obligatorio'});if(liters===null||liters<=0)return res.status(400).json({error:'liters debe ser mayor que cero'});if(price===null||price<=0)return res.status(400).json({error:'price_clp debe ser mayor que cero'});if(odometer===null||odometer<0)return res.status(400).json({error:'odometer_km no válido'});if(date===false)return res.status(400).json({error:'Fecha no válida'});const client=await pool.connect();try{await client.query('BEGIN');const truck=(await client.query('select id,company_id,patente from trucks where id=$1 and company_id=$2 for share',[truckId,cid])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}const created=(await client.query('insert into fuel(company_id,date,truck,truck_id,liters,price_clp,total_clp,station,odometer_km) values($1,coalesce($2,current_date),$3,$4,$5,$6,$5*$6,$7,$8) returning *',[cid,date,truck.patente,truck.id,liters,price,clean(b.station)||null,odometer])).rows[0];const result={...created,truck_patente:truck.patente};await writeAudit(client,req,{companyId:cid,action:'create',entity:'fuel',entityId:created.id,afterData:result});await client.query('COMMIT');res.status(201).json(result)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo registrar el combustible'})}finally{client.release()}});

 app.get('/api/fleet/maintenance',requirePermission('maintenance.manage'),async(req,res)=>{try{const s=scope(req,'m');const values=[...s.values],inner=[s.sql],outer=[];if(req.query.truck_id){const truckId=parseFuelNumber(req.query.truck_id);if(!Number.isInteger(truckId)||truckId<1)return res.status(400).json({error:'truck_id no válido'});values.push(truckId);inner.push(`m.truck_id=$${values.length}`)}if(req.query.status){if(!MAINTENANCE_STATUSES.includes(req.query.status))return res.status(400).json({error:'status no válido'});values.push(req.query.status);outer.push(`q.status=$${values.length}`)}if(req.query.maintenance_type){if(!MAINTENANCE_TYPES.includes(req.query.maintenance_type))return res.status(400).json({error:'maintenance_type no válido'});values.push(req.query.maintenance_type);outer.push(`q.maintenance_type=$${values.length}`)}if(req.query.from){const from=parseFuelDate(req.query.from);if(!from)return res.status(400).json({error:'Fecha inicial no válida'});values.push(from);outer.push(`q.effective_date >= $${values.length}`)}if(req.query.to){const to=parseFuelDate(req.query.to);if(!to)return res.status(400).json({error:'Fecha final no válida'});values.push(to);outer.push(`q.effective_date <= $${values.length}`)}if(req.query.upcoming==='true')outer.push('q.is_upcoming=true');if(req.query.overdue==='true')outer.push('q.is_overdue=true');const query=`select * from (select m.*,coalesce(t.patente,m.truck) truck_patente,coalesce(m.performed_at,m.due,m.next_due_date,m.created_at::date) effective_date,case when m.truck_id is null then null else lag(m.odometer_km) over(partition by m.truck_id order by coalesce(m.performed_at,m.due,m.created_at::date) asc,m.id asc) end previous_odometer_km,(m.status not in ('Completada','Cancelada') and m.next_due_date between current_date and current_date+7) is_upcoming,(m.status not in ('Completada','Cancelada') and ((coalesce(m.next_due_date,m.due) is not null and coalesce(m.next_due_date,m.due)<current_date) or (m.next_due_odometer_km is not null and t.km>=m.next_due_odometer_km))) is_overdue from maintenance m left join trucks t on t.id=m.truck_id and t.company_id=m.company_id where ${inner.join(' and ')}) q${outer.length?` where ${outer.join(' and ')}`:''} order by q.effective_date desc nulls last,q.id desc limit 1000`;const r=await pool.query(query,values);const result=maintenanceMetrics(r.rows);res.json(req.query.include_summary==='true'?result:result.records)}catch(e){res.status(500).json({error:'No se pudieron cargar las mantenciones'})}});
 app.post('/api/fleet/maintenance',requirePermission('maintenance.manage'),async(req,res)=>{const b=body(req),cid=isAdmin(req)?parseFuelNumber(b.company_id):userCompany(req);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});const input=maintenanceInput(b);if(input.error)return res.status(400).json({error:input.error});const client=await pool.connect();try{await client.query('BEGIN');const truck=(await client.query('select id,company_id,patente from trucks where id=$1 and company_id=$2 for share',[input.truckId,cid])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}const created=(await client.query('insert into maintenance(company_id,truck,truck_id,item,due,cost_clp,status,maintenance_type,performed_at,odometer_km,workshop,notes,parts_description,parts_cost_clp,labor_cost_clp,next_due_date,next_due_odometer_km,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,now(),now()) returning *',[cid,truck.patente,truck.id,input.item,input.due,input.total,input.status,input.type,input.performed,input.odometer,input.workshop,input.notes,input.partsDescription,input.partsCost,input.laborCost,input.nextDue,input.nextOdometer])).rows[0];const result={...created,truck_patente:truck.patente};await writeAudit(client,req,{companyId:cid,action:'create',entity:'maintenance',entityId:created.id,afterData:result});await client.query('COMMIT');res.status(201).json(result)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo registrar la mantención'})}finally{client.release()}});
 app.patch('/api/fleet/maintenance/:id',requirePermission('maintenance.manage'),async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const s=scope(req,'m',2);const before=(await client.query(`select m.*,coalesce(t.patente,m.truck) truck_patente from maintenance m left join trucks t on t.id=m.truck_id and t.company_id=m.company_id where m.id=$1 and ${s.sql} for update of m`,[Number(req.params.id),...s.values])).rows[0];if(!before){await client.query('ROLLBACK');return res.sendStatus(404)}const input=maintenanceInput(body(req),{partial:true,current:before});if(input.error){await client.query('ROLLBACK');return res.status(400).json({error:input.error})}const truck=(await client.query('select id,company_id,patente from trucks where id=$1 and company_id=$2 for share',[input.truckId,before.company_id])).rows[0];if(!truck){await client.query('ROLLBACK');return res.sendStatus(404)}const after=(await client.query('update maintenance set truck=$1,truck_id=$2,item=$3,due=$4,cost_clp=$5,status=$6,maintenance_type=$7,performed_at=$8,odometer_km=$9,workshop=$10,notes=$11,parts_description=$12,parts_cost_clp=$13,labor_cost_clp=$14,next_due_date=$15,next_due_odometer_km=$16,updated_at=now() where id=$17 returning *',[truck.patente,truck.id,input.item,input.due,input.total,input.status,input.type,input.performed,input.odometer,input.workshop,input.notes,input.partsDescription,input.partsCost,input.laborCost,input.nextDue,input.nextOdometer,Number(req.params.id)])).rows[0];const result={...after,truck_patente:truck.patente};await writeAudit(client,req,{companyId:before.company_id,action:'update',entity:'maintenance',entityId:before.id,beforeData:before,afterData:result});await client.query('COMMIT');res.json(result)}catch(e){await client.query('ROLLBACK');res.status(400).json({error:'No se pudo actualizar la mantención'})}finally{client.release()}});

 app.get('/api/fleet/alerts',requirePermission('dashboard.read'),async(req,res)=>{try{const s=scope(req,'a');const r=await pool.query(`select a.* from alerts a where ${s.sql} order by a.resolved asc,a.created_at desc limit 500`,s.values);res.json(r.rows)}catch(e){res.status(500).json({error:'No se pudieron cargar las alertas'})}});
 app.post('/api/fleet/alerts/:id/resolve',requirePermission('fleet.manage'),async(req,res)=>{try{const s=scope(req,'a',2);const r=await pool.query(`update alerts set resolved=true where id=$1 and ${s.sql} returning *`,[req.params.id,...s.values]);if(!r.rowCount)return res.sendStatus(404);res.json(r.rows[0])}catch(e){res.status(400).json({error:'No se pudo resolver la alerta'})}});
 app.post('/api/fleet/alerts/generate',requirePermission('fleet.manage'),async(req,res)=>{try{const cid=isAdmin(req)?req.body?.company_id:userCompany(req);if(!cid)return res.status(400).json({error:'company_id es obligatorio'});const created=[];const exp=await pool.query("select id,company_id,patente,status,location from trucks where company_id=$1 and status='Mantención'",[cid]);for(const t of exp.rows){const r=await pool.query("insert into alerts(company_id,level,title,text,resolved,created_at) select $1,'warning','Camión en mantención',$2,false,now() where not exists(select 1 from alerts where company_id=$1 and title='Camión en mantención' and text=$2 and resolved=false) returning *",[cid,`El camión ${t.patente} figura en Mantención.`]);if(r.rowCount)created.push(r.rows[0])}const due=await pool.query("select id,truck,item,due from maintenance where company_id=$1 and due is not null and due<=current_date+interval '7 days' and status<>'Completada'",[cid]);for(const m of due.rows){const r=await pool.query("insert into alerts(company_id,level,title,text,resolved,created_at) select $1,case when due<current_date then 'critical' else 'warning' end,'Mantención próxima o vencida',$2,false,now() where not exists(select 1 from alerts where company_id=$1 and title='Mantención próxima o vencida' and text=$2 and resolved=false) returning *",[cid,`Mantención ${m.item||''} del camión ${m.truck||''}: ${m.due}.`]);if(r.rowCount)created.push(r.rows[0])}res.json({created:created.length,alerts:created})}catch(e){res.status(500).json({error:'No se pudieron generar las alertas'})}});
}
module.exports={registerFleetRoutes};
