const express=require("express");
const {Pool}=require("pg");
const fs=require("fs");
const path=require("path");
const {registerCoreRoutes,initializeCorePlatform}=require("./core-api");
const {registerAuthRoutes,authMiddleware}=require("./auth");
const app=express();const PORT=Number(process.env.PORT||3000);const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL){console.error("Falta DATABASE_URL. Define la variable de entorno antes de iniciar FleetChile.");process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,max:Number(process.env.DB_POOL_MAX||10),idleTimeoutMillis:30000,connectionTimeoutMillis:10000,ssl:process.env.DATABASE_SSL==="true"?{rejectUnauthorized:false}:undefined});
app.disable("x-powered-by");app.set("trust proxy",1);app.use((req,res,next)=>{res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Frame-Options","SAMEORIGIN");res.setHeader("Referrer-Policy","strict-origin-when-cross-origin");res.setHeader("Cache-Control",req.path.startsWith("/api/")?"no-store":"no-cache");next()});app.use(express.json({limit:"2mb"}));app.use(express.static(path.join(__dirname,"public"),{maxAge:0}));
const tables=["trucks","drivers","routes","loads","maintenance","fuel","alerts","telemetry"];const safeTable=name=>tables.includes(name);
registerAuthRoutes(app,pool);
app.get("/api/health",async(req,res)=>{try{await pool.query("select 1");res.json({ok:true,service:"fleetchile",time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,service:"fleetchile",error:"database_unavailable"})}});
app.use("/api",authMiddleware.bind(null,pool));
// Las rutas específicas del núcleo deben registrarse antes del comodín /api/:table.
// De lo contrario, /api/clients y /api/trips serían interceptadas por el comodín y devolverían 404.
registerCoreRoutes(app,pool);
app.get("/api/dashboard",async(req,res)=>{try{const q=async sql=>Number((await pool.query(sql)).rows[0].n||0);res.json({trucks:await q("select count(*) n from trucks"),enroute:await q("select count(*) n from trucks where status='En ruta'"),loads:await q("select count(*) n from loads"),alerts:await q("select count(*) n from alerts where resolved=false"),fuel:await q("select coalesce(sum(total_clp),0) n from fuel"),km:await q("select coalesce(sum(km),0) n from trucks")})}catch(e){res.status(500).json({error:"No se pudo cargar el dashboard"})}});
app.get("/api/:table",async(req,res)=>{if(!safeTable(req.params.table))return res.sendStatus(404);try{res.json((await pool.query(`select * from ${req.params.table} order by id desc`)).rows)}catch(e){res.status(500).json({error:"No se pudo consultar la información"})}});
app.get("/api/trucks/:id/history",async(req,res)=>{try{res.json((await pool.query("select * from telemetry where truck_id=$1 order by recorded_at desc limit 100",[req.params.id])).rows)}catch(e){res.status(500).json({error:"No se pudo consultar el historial GPS"})}});
app.post("/api/trucks",async(req,res)=>{const{patente,tipo,capacidad_t,driver,status="Disponible",km=0,lat=null,lng=null,location=""}=req.body;if(!patente||!tipo||capacidad_t===undefined)return res.status(400).json({error:"patente, tipo y capacidad_t son obligatorios"});try{const r=await pool.query("insert into trucks(patente,tipo,capacidad_t,driver,status,km,lat,lng,location) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *",[patente.trim().toUpperCase(),tipo,capacidad_t,driver||null,status,km,lat,lng,location]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:e.code==="23505"?"La patente ya existe":"No se pudo crear el camión"})}});
app.patch("/api/trucks/:id/location",async(req,res)=>{const{lat,lng,location,km,status,speed_kmh=0}=req.body;if(lat===undefined||lng===undefined)return res.status(400).json({error:"lat y lng son obligatorios"});try{const r=await pool.query("update trucks set lat=coalesce($1,lat),lng=coalesce($2,lng),location=coalesce($3,location),km=coalesce($4,km),status=coalesce($5,status) where id=$6 returning *",[lat,lng,location,km,status,req.params.id]);if(!r.rowCount)return res.sendStatus(404);await pool.query("insert into telemetry(truck_id,lat,lng,speed_kmh,km,recorded_at) values($1,$2,$3,$4,$5,now())",[req.params.id,lat,lng,speed_kmh,km??r.rows[0].km??0]);res.json(r.rows[0])}catch(e){res.status(400).json({error:"No se pudo actualizar la posición GPS"})}});
app.post("/api/routes",async(req,res)=>{const{truck,origin,destination,distance_km=0,progress=0,status="Planificada",eta=null}=req.body;try{const r=await pool.query("insert into routes(truck,origin,destination,distance_km,progress,status,eta) values($1,$2,$3,$4,$5,$6,$7) returning *",[truck||null,origin||null,destination||null,distance_km,progress,status,eta]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:"No se pudo crear la ruta"})}});
app.post("/api/loads",async(req,res)=>{const{client,guide,cargo,weight_kg=0,volume_m3=0,value_clp=0,truck,origin,destination,status="Planificada"}=req.body;try{const r=await pool.query("insert into loads(client,guide,cargo,weight_kg,volume_m3,value_clp,truck,origin,destination,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *",[client||null,guide||null,cargo||null,weight_kg,volume_m3,value_clp,truck||null,origin||null,destination||null,status]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:"No se pudo crear la carga"})}});
app.post("/api/fuel",async(req,res)=>{const{date,truck,liters,price_clp,station}=req.body;try{const r=await pool.query("insert into fuel(date,truck,liters,price_clp,total_clp,station) values($1,$2,$3,$4,$3*$4,$5) returning *",[date||null,truck||null,liters||0,price_clp||0,station||null]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:"No se pudo registrar el combustible"})}});
app.post("/api/maintenance",async(req,res)=>{const{truck,item,due,cost_clp=0,status="Pendiente"}=req.body;try{const r=await pool.query("insert into maintenance(truck,item,due,cost_clp,status) values($1,$2,$3,$4,$5) returning *",[truck||null,item||null,due||null,cost_clp,status]);res.status(201).json(r.rows[0])}catch(e){res.status(400).json({error:"No se pudo registrar la mantención"})}});
app.delete("/api/:table/:id",async(req,res)=>{if(!safeTable(req.params.table))return res.sendStatus(404);try{const r=await pool.query(`delete from ${req.params.table} where id=$1`,[req.params.id]);if(!r.rowCount)return res.sendStatus(404);res.sendStatus(204)}catch(e){res.status(400).json({error:"No se pudo eliminar el registro"})}});
app.use((req,res,next)=>{if(req.method==="GET"&&!req.path.startsWith("/api/"))return res.sendFile(path.join(__dirname,"public","index.html"));next()});
async function initializeDatabase(){const schema=fs.readFileSync(path.join(__dirname,"schema.sql"),"utf8");await pool.query(schema);const{rows}=await pool.query("select count(*)::int as count from trucks");if(rows[0].count===0){const seed=fs.readFileSync(path.join(__dirname,"seed.sql"),"utf8");await pool.query(seed);console.log("Base de datos inicializada con datos demo.")}await initializeCorePlatform(pool);const authMigration=fs.readFileSync(path.join(__dirname,"migrations","003_auth_rbac.sql"),"utf8");await pool.query(authMigration)}
async function start(){await initializeDatabase();const server=app.listen(PORT,()=>console.log(`FleetChile Pro escuchando en puerto ${PORT}`));const shutdown=async()=>{server.close(async()=>{await pool.end();process.exit(0)})};process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown)}
start().catch(err=>{console.error("No se pudo iniciar FleetChile:",err.message);process.exit(1)});