const test=require('node:test');
const assert=require('node:assert/strict');
const {registerOperationsRoutes}=require('../operations-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});routes.route=(method,path)=>routes.find(r=>r.method===method&&r.path===path);return routes}
function response(){return {statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,req){const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
const driver={id:8,role_code:'driver',company_id:10,driver_id:4};
function assertNoSecrets(payload){const text=JSON.stringify(payload);assert.equal(text.includes('storage_key'),false);assert.equal(text.includes('s3.amazonaws'),false);assert.equal(text.includes('data:image/'),false);}
const signature='iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAGklEQVQ4jWP4TyFgGDXg/2gY/B8Ng//DIgwAXXj8LuMlDaEAAAAASUVORK5CYII=';
;
function pool({trip={id:7,company_id:10,driver_id:4,truck_id:3},load={id:9,trip_id:7,status:'Planificada'},existing=null,closed=null,files=[],fail=''}={}){const calls=[];const client={calls,async query(sql,values=[]){calls.push({sql,values});if(fail&&sql.includes(fail))throw Error('forced');if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return {rows:[],rowCount:0};
  if(sql.startsWith('update trip_delivery_proofs'))return {rows:[{id:21,trip_id:7,load_id:9,status:'CLOSED',client_submission_id:'submission-1',recipient_name:'Receptor',created_by:8}],rowCount:1};
  if(sql.includes('from delivery_proof_files where'))return {rows:files,rowCount:files.length};
  if(sql.includes('from trips where')){const ok=trip&&String(trip.id)===String(values[0])&&trip.company_id===values[1]&&trip.driver_id===values[2];return {rows:ok?[trip]:[],rowCount:ok?1:0}}
  if(sql.includes('from trip_delivery_proofs where trip_id=$1 and client_submission_id=$2'))return {rows:existing?[existing]:[],rowCount:existing?1:0};
  if(sql.includes('from trip_loads where id=$1 and trip_id=$2')){const ok=load&&String(load.id)===String(values[0])&&String(load.trip_id)===String(values[1]);return {rows:ok?[load]:[],rowCount:ok?1:0}}
  if(sql.startsWith('select id from trip_delivery_proofs'))return {rows:closed?[closed]:[],rowCount:closed?1:0};
  if(sql.startsWith('insert into trip_delivery_proofs'))return {rows:[{id:21,trip_id:7,load_id:9,status:'DRAFT',client_submission_id:values[2],recipient_name:values[3],created_by:values[9]}],rowCount:1};
  if(sql.startsWith('insert into delivery_proof_files'))return {rows:[],rowCount:1};
  if(sql.startsWith('update trip_loads'))return {rows:[{id:9,trip_id:7,status:'Entregada'}],rowCount:1};
  if(sql.startsWith('insert into trip_events')||sql.startsWith('insert into audit_logs'))return {rows:[],rowCount:1};
  if(sql.includes('from trip_loads l left join trip_delivery_proofs'))return {rows:[],rowCount:0};
  throw Error(`unexpected SQL: ${sql}`)},release(){}};return {calls,async query(...args){return client.query(...args)},async connect(){return client}}
}
async function routes(p,storage={put:async()=>{},delete:async()=>{}}){const a=app();await registerOperationsRoutes(a,p,{storage});return a}
const req=(overrides={})=>({user:driver,params:{id:'7'},body:{load_id:9,client_submission_id:'submission-1',recipient_name:'Receptor',recipient_rut:'1-9',notes:'Entregado',signature},...overrides});
test('driver crea POD cerrado con firma, entrega carga y registra trazabilidad',async()=>{const p=pool(),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,201);assert.equal(r.payload.status,'CLOSED');assert.ok(p.calls.some(x=>x.sql.startsWith('insert into delivery_proof_files')));assert.ok(p.calls.some(x=>x.sql.startsWith('update trip_loads')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_events')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')));assert.equal(p.calls.at(-1).sql,'COMMIT')});
test('GET entregas aplica company y driver scope',async()=>{const a=await routes(pool()),r=await invoke(a.route('get','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,200);for(const trip of [{id:7,company_id:20,driver_id:4},{id:7,company_id:10,driver_id:5}]){const x=await routes(pool({trip}));assert.equal((await invoke(x.route('get','/api/driver/trips/:id/deliveries'),req())).statusCode,404)}});
test('GET entregas expone metadata segura de evidencias sin storage_key',async()=>{const p=pool(),original=p.query.bind(p);p.query=async(sql,...args)=>sql.includes('from trip_loads l')?{rows:[{id:9,status:'Planificada',deliveries:[{id:30,status:'DRAFT',evidence:[{type:'signature',exists:true,mime_type:'image/png',size:32,created_at:'2026-01-01'}]}]}],rowCount:1}:original(sql,...args);const a=await routes(p),r=await invoke(a.route('get','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,200);const evidence=r.payload.deliveries[0].deliveries[0].evidence[0];assert.deepEqual(evidence,{type:'signature',exists:true,mime_type:'image/png',size:32,created_at:'2026-01-01'});assert.equal('storage_key' in evidence,false)});
test('carga inexistente, ajena, entregada o con POD cerrado se rechaza',async()=>{for(const options of [{load:null},{trip:{id:8,company_id:10,driver_id:4,truck_id:3},load:{id:9,trip_id:8,status:'Planificada'}},{load:{id:9,trip_id:7,status:'Entregada'}},{closed:{id:20,status:'CLOSED'}}]){const x=await routes(pool(options));const r=await invoke(x.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,options.closed||options.load?.status==='Entregada'?409:404)}});
-test('driver crea POD cerrado con firma, entrega carga y registra trazabilidad',async()=>{const p=pool(),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,201);assert.equal(r.payload.status,'CLOSED');assert.ok(p.calls.some(x=>x.sql.startsWith('insert into delivery_proof_files')));assert.ok(p.calls.some(x=>x.sql.startsWith('update trip_loads')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_events')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')));assert.equal(p.calls.at(-1).sql,'COMMIT')});
test('driver crea POD cerrado con firma, entrega carga y registra trazabilidad',async()=>{const p=pool(),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,201);assert.equal(r.payload.status,'CLOSED');assertNoSecrets(r.payload);assert.ok(p.calls.some(x=>x.sql.startsWith('insert into delivery_proof_files')));assert.ok(p.calls.some(x=>x.sql.startsWith('update trip_loads')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_events')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')));assert.equal(p.calls.at(-1).sql,'COMMIT')});
test('reintento con client_submission_id devuelve POD existente sin duplicar',async()=>{const existing={id:21,load_id:9,status:'CLOSED',client_submission_id:'submission-1'},p=pool({existing}),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,200);assert.deepEqual(r.payload,{...existing,files:[]});assertNoSecrets(r.payload);assert.equal(p.calls.some(x=>x.sql.startsWith('insert into delivery_proof_files')),false)});
test('DRAFT existente con el mismo submission se reanuda sin crear otro POD',async()=>{const existing={id:30,load_id:9,status:'DRAFT',client_submission_id:'submission-1'},p=pool({existing}),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,201);assert.equal(r.payload.status,'CLOSED');assertNoSecrets(r.payload);assert.equal(p.calls.filter(x=>x.sql.startsWith('insert into trip_delivery_proofs')).length,0)});
test('DRAFT existente incompatible con load_id se rechaza determinísticamente',async()=>{const existing={id:30,load_id:88,status:'DRAFT',client_submission_id:'submission-1'},p=pool({existing}),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,409);assert.equal(p.calls.some(x=>x.sql.startsWith('insert into trip_delivery_proofs')),false)});
test('DRAFT con firma ya almacenada puede cerrarse sin reenviar la firma',async()=>{const existing={id:30,load_id:9,status:'DRAFT',client_submission_id:'submission-1'},files=[{id:1,type:'signature',storage_key:'private/signature',mime_type:'image/png',size:32,sha256:'a'.repeat(64),created_by:8}],p=pool({existing,files}),a=await routes(p,{head:async()=>({})}),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({body:{load_id:9,client_submission_id:'submission-1',recipient_name:'Receptor'}}));assert.equal(r.statusCode,201);assert.equal(r.payload.status,'CLOSED');assert.equal(p.calls.filter(x=>x.sql.startsWith('insert into delivery_proof_files')).length,0)});
test('el cliente PostgreSQL se libera exactamente una vez en éxito y excepción',async()=>{for(const fail of ['', 'insert into trip_events']){const p=pool({fail}),original=p.connect.bind(p);let releases=0;p.connect=async()=>{const c=await original();const release=c.release.bind(c);c.release=()=>{releases++;release()};return c};const a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({body:{...req().body,client_submission_id:`release-${fail||'ok'}`}}));assert.equal(r.statusCode,fail?400:201);assert.equal(releases,1)}});
test('identidad enviada por frontend es ignorada',async()=>{const p=pool(),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({body:{load_id:9,client_submission_id:'s2',recipient_name:'R',signature,company_id:99,driver_id:99,user_id:99,truck_id:99}}));assert.equal(r.statusCode,201);const q=p.calls.find(x=>x.sql.includes('from trips where'));assert.deepEqual(q.values,['7',10,4])});
test('driver sin asociación, usuario no driver y admin reciben 403',async()=>{for(const user of [{...driver,driver_id:null},{...driver,role_code:'operations'},{...driver,role_code:'admin'}]){const a=await routes(pool());assert.equal((await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({user}))).statusCode,403)}});
test('firma ausente, vacía, inválida, grande o con dimensiones inválidas se rechaza',async()=>{const cases=[{}, {signature:''},{signature:'not-base64'},{signature:Buffer.alloc(600000).toString('base64')},{signature:(()=>{const b=Buffer.alloc(32);b.set([137,80,78,71,13,10,26,10]);b.writeUInt32BE(8,16);b.writeUInt32BE(8,20);return b.toString('base64')})()}];for(const [i,body] of cases.entries()){const base={...req().body};delete base.signature;const a=await routes(pool());assert.equal((await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({body:{...base,...body}}))).statusCode,400,String(i))}});
test('fotografía opcional válida y formatos falsos son controlados',async()=>{const p=pool(),a=await routes(p),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({body:{...req().body,photo:signature}}));assert.equal(r.statusCode,201);const bad=await routes(pool());assert.equal((await invoke(bad.route('post','/api/driver/trips/:id/deliveries'),req({body:{...req().body,client_submission_id:'bad',photo:'data:image/jpeg;base64,not-real'}}))).statusCode,400)});
test('rollback y compensación se ejecutan ante fallo transaccional',async()=>{const deleted=[];const storage={put:async()=>{},delete:async key=>deleted.push(key)};for(const fail of ['insert into delivery_proof_files','update trip_loads','insert into trip_events','insert into audit_logs']){const p=pool({fail}),a=await routes(p,storage),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({body:{...req().body,client_submission_id:`fail-${fail}`}}));assert.equal(r.statusCode,400,fail);assert.equal(p.calls.at(-1).sql,'ROLLBACK',fail);assert.equal(p.calls.some(x=>x.sql==='COMMIT'),false,fail)}assert.ok(deleted.length>0)});
test('upload ambiguo registra la key antes de put y compensa incluso si delete falla',async()=>{const deleted=[];const storage={put:async()=>{throw Error('ambiguous upload')},delete:async key=>{deleted.push(key);throw Error('delete unavailable')}};const p=pool(),a=await routes(p,storage),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req({body:{...req().body,client_submission_id:'ambiguous'}}));assert.equal(r.statusCode,400);assert.equal(deleted.length,1);assert.equal(p.calls.at(-1).sql,'ROLLBACK')});
test('POD VOID responde 409 sin mutar ni trazar entrega',async()=>{const p=pool({existing:{id:30,load_id:9,status:'VOID',client_submission_id:'submission-1'}}),a=await routes(p,{head:async()=>({})}),r=await invoke(a.route('post','/api/driver/trips/:id/deliveries'),req());assert.equal(r.statusCode,409);assert.equal(p.calls.some(x=>x.sql.startsWith('update trip_delivery_proofs')),false);assert.equal(p.calls.some(x=>x.sql.startsWith('update trip_loads')),false);assert.equal(p.calls.some(x=>x.sql.startsWith('insert into trip_events')),false);assert.equal(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')),false)});
