const test=require('node:test');
const assert=require('node:assert/strict');
const {registerOperationsRoutes}=require('../operations-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});routes.route=(method,path)=>routes.find(r=>r.method===method&&r.path===path);return routes}
function response(){return {statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,req){const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
const user={id:8,role_code:'driver',company_id:10,driver_id:4};
function pool(initial='Asignado',trip={id:7,company_id:10,driver_id:4},failOn=''){let state=initial;const original=initial;const calls=[];const client={calls,async query(sql,values=[]){calls.push({sql,values});if(failOn&&sql.toLowerCase().includes(failOn))throw new Error('forced failure');if(sql==='BEGIN'||sql==='COMMIT')return {rows:[],rowCount:0};if(sql==='ROLLBACK'){state=original;return {rows:[],rowCount:0};}if(sql.startsWith('select status from trips'))return {rows:trip.company_id===values[1]&&trip.driver_id===values[2]?[{status:state}]:[],rowCount:1};if(sql.startsWith('select * from trips'))return {rows:trip.id===Number(values[0])&&trip.company_id===values[1]&&trip.driver_id===values[2]?[{...trip,status:state}]:[],rowCount:1};if(sql.startsWith('update trips')){state=values[0];return {rows:[{...trip,status:state}],rowCount:1};}if(sql.startsWith('insert into'))return {rows:[],rowCount:1};throw new Error(`Consulta inesperada: ${sql}`)},release(){}};return {calls,get state(){return state},async query(...args){return client.query(...args)},async connect(){return client}}}
async function routesFor(p){const a=app();await registerOperationsRoutes(a,p);return a}
async function change(current,target,userOverride=user,p=pool(current)){const a=await routesFor(p);return {res:await invoke(a.route('patch','/api/driver/trips/:id/status'),{user:userOverride,params:{id:'7'},body:{status:target,company_id:99,driver_id:99}}),pool:p}}
test('driver ejecuta todas las transiciones válidas',async()=>{for(const [from,to] of [['Asignado','En carga'],['Asignado','En tránsito'],['En carga','En tránsito'],['En tránsito','Detenido'],['Detenido','En tránsito'],['En tránsito','Llegó a destino'],['Llegó a destino','Descargando'],['Descargando','Completado']])assert.equal((await change(from,to)).res.statusCode,200,`${from} -> ${to}`)});
test('allowed-statuses devuelve únicamente la matriz del estado real',async()=>{const expected={Asignado:['En carga','En tránsito'],'En carga':['En tránsito'],'En tránsito':['Detenido','Llegó a destino'],Detenido:['En tránsito'],'Llegó a destino':['Descargando'],Descargando:['Completado'],Planificado:[],Completado:[],Cancelado:[]};for(const [current,allowed] of Object.entries(expected)){const a=await routesFor(pool(current));const res=await invoke(a.route('get','/api/driver/trips/:id/allowed-statuses'),{user,params:{id:'7'}});assert.equal(res.statusCode,200);assert.deepEqual(res.payload,{status:current,allowed_statuses:allowed})}});
test('allowed-statuses aplica aislamiento y requiere driver asociado',async()=>{const other=await routesFor(pool('Asignado',{id:8,company_id:10,driver_id:5}));assert.equal((await invoke(other.route('get','/api/driver/trips/:id/allowed-statuses'),{user,params:{id:'8'}})).statusCode,404);const foreign=await routesFor(pool('Asignado',{id:9,company_id:20,driver_id:6}));assert.equal((await invoke(foreign.route('get','/api/driver/trips/:id/allowed-statuses'),{user,params:{id:'9'}})).statusCode,404);for(const u of [{...user,driver_id:null},{role_code:'viewer',company_id:10,driver_id:4},{role_code:'admin',company_id:null,driver_id:null}]){const a=await routesFor(pool());assert.equal((await invoke(a.route('get','/api/driver/trips/:id/allowed-statuses'),{user:u,params:{id:'7'}})).statusCode,403)}});
test('rechaza saltos y estados terminales',async()=>{for(const [from,to] of [['Planificado','Asignado'],['Asignado','Completado'],['En carga','Completado'],['Detenido','Llegó a destino'],['Completado','En tránsito'],['Cancelado','Asignado']])assert.equal((await change(from,to)).res.statusCode,409,`${from} -> ${to}`)});
test('estado desconocido devuelve 400',async()=>{assert.equal((await change('Asignado','Inventado')).res.statusCode,400)});
test('aislamiento distingue Empresa A/Drivers A-B y Empresa B/Driver C',async()=>{const cases=[{id:1,company_id:10,driver_id:4,ok:200},{id:2,company_id:10,driver_id:5,ok:404},{id:3,company_id:20,driver_id:6,ok:404}];for(const item of cases){const p=pool('Asignado',item);const a=await routesFor(p);const res=await invoke(a.route('patch','/api/driver/trips/:id/status'),{user,params:{id:String(item.id)},body:{status:'En tránsito',driver_id:999,company_id:999}});assert.equal(res.statusCode,item.ok)}});
test('driver sin asociación, no driver y admin reciben 403',async()=>{for(const u of [{...user,driver_id:null},{role_code:'viewer',company_id:10,driver_id:4},{role_code:'admin',company_id:null,driver_id:null}])assert.equal((await change('Asignado','En carga',u)).res.statusCode,403)});
test('trip_id manipulado permanece bajo scope',async()=>{const p=pool('Asignado',{id:7,company_id:10,driver_id:4});const a=await routesFor(p);assert.equal((await invoke(a.route('patch','/api/driver/trips/:id/status'),{user,params:{id:'99'},body:{status:'En carga'}})).statusCode,404);assert.deepEqual(p.calls.find(x=>x.sql.startsWith('select * from trips')).values,['99',10,4])});
test('transición registra fechas, historial, evento y auditoría en una transacción',async()=>{const {res,pool:p}=await change('Asignado','En tránsito');assert.equal(res.statusCode,200);assert.equal(p.calls[0].sql,'BEGIN');assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_status_history')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_events')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')));assert.equal(p.calls.at(-1).sql,'COMMIT');assert.match(p.calls.find(x=>x.sql.startsWith('update trips')).sql,/actual_departure=case when \$1='En tránsito'/)});
test('rollback revierte ante fallo de historial, evento o auditoría',async()=>{for(const fail of ['trip_status_history','trip_events','audit_logs']){const p=pool('Asignado',undefined,fail);const {res}=await change('Asignado','En tránsito',user,p);assert.equal(res.statusCode,400,fail);assert.equal(p.state,'Asignado');assert.equal(p.calls.at(-1).sql,'ROLLBACK');assert.equal(p.calls.some(x=>x.sql==='COMMIT'),false)}});
test('segunda transición reevalúa el estado actual',async()=>{const p=pool('Asignado');const a=await routesFor(p);const route=a.route('patch','/api/driver/trips/:id/status');assert.equal((await invoke(route,{user,params:{id:'7'},body:{status:'En tránsito'}},p)).statusCode,200);assert.equal((await invoke(route,{user,params:{id:'7'},body:{status:'En carga'}},p)).statusCode,409)});
test('completar no modifica ubicación ni retorno del camión',async()=>{const {res,pool:p}=await change('Descargando','Completado');assert.equal(res.statusCode,200);assert.equal(p.calls.some(x=>x.sql.includes('trucks')),false);assert.match(p.calls.find(x=>x.sql.startsWith('update trips')).sql,/actual_arrival=case when \$1='Completado'/)});
