const test=require('node:test');
const assert=require('node:assert/strict');
const {registerOperationsRoutes}=require('../operations-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});routes.route=(m,p)=>routes.find(x=>x.method===m&&x.path===p);return routes}
function res(){return {statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,req){const out=res();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,out,next)};await next();return out}
const user={id:8,role_code:'driver',company_id:10,driver_id:4};
function pool({trip=true,checkStatus='Pendiente',fail='' }={}){const calls=[];let status=checkStatus;const client={async query(sql,v=[]){calls.push({sql,v});if(fail&&sql.includes(fail))throw Error('forced');if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return {rows:[],rowCount:0};if(sql.includes('from trips'))return {rows:trip?[{id:7,company_id:10,driver_id:4,truck_id:3,trip_driver_id:4,trip_truck_id:3}]:[],rowCount:trip?1:0};if(sql.includes('from vehicle_checklists where trip_id'))return {rows:[{id:11,trip_id:7,truck_id:3,driver_id:4,status,items:[],observations:null}],rowCount:1};if(sql.includes('from vehicle_checklists vc join trips'))return {rows:[{id:11,trip_id:7,company_id:10,driver_id:4,trip_driver_id:4,truck_id:3,status,items:[],observations:null}],rowCount:1};if(sql.startsWith('insert into vehicle_checklists'))return {rows:[{id:12,trip_id:7,truck_id:3,driver_id:4,status:'Pendiente',items:[],observations:null}],rowCount:1};if(sql.startsWith('update vehicle_checklists')){status=v[0];return {rows:[{id:11,trip_id:7,truck_id:3,driver_id:4,status,items:v[1],observations:v[2]}],rowCount:1};}if(sql.startsWith('insert into'))return {rows:[],rowCount:1};throw Error(sql)},release(){}};return {calls,async query(...a){return client.query(...a)},async connect(){return client}}}
async function setup(p){const a=app();await registerOperationsRoutes(a,p);return a}
const req=(overrides={})=>({user,params:{id:'7'},body:{},query:{},...overrides});
test('driver consulta y crea checklist propio derivando identidad',async()=>{const p=pool();const a=await setup(p);let r=await invoke(a.route('get','/api/driver/trips/:id/checklist'),req());assert.equal(r.statusCode,200);assert.equal(r.payload.checklists[0].id,11);r=await invoke(a.route('post','/api/driver/trips/:id/checklist'),req({body:{driver_id:99,company_id:99,truck_id:99,items:[{item:'Frenos',applicable:false} ]}}));assert.equal(r.statusCode,201);const insert=p.calls.find(x=>x.sql.startsWith('insert into vehicle_checklists'));assert.deepEqual(insert.v.slice(0,3),[3,4,7])});
test('scope y acceso driver son obligatorios',async()=>{const p=pool({trip:false});const a=await setup(p);assert.equal((await invoke(a.route('get','/api/driver/trips/:id/checklist'),req())).statusCode,404);for(const u of [{...user,driver_id:null},{...user,role_code:'operations'},{...user,role_code:'admin'}])assert.equal((await invoke(a.route('get','/api/driver/trips/:id/checklist'),req({user:u}))).statusCode,403)});
test('checklist pendiente puede cerrarse rechazado y crea alerta/evento/auditoria',async()=>{const p=pool();const a=await setup(p);const r=await invoke(a.route('patch','/api/driver/checklists/:id'),req({params:{id:'11'},body:{status:'Rechazado',items:[{item:'Frenos',applicable:true,result:'Falla'}],observations:'Revisar'}}));assert.equal(r.statusCode,200);assert.equal(r.payload.status,'Rechazado');assert.ok(p.calls.some(x=>x.sql.includes("'checklist'")));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_events')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')))});
test('checklist cerrado no puede sobrescribirse y nueva inspección es otro registro',async()=>{const closed=await setup(pool({checkStatus:'Aprobado'}));assert.equal((await invoke(closed.route('patch','/api/driver/checklists/:id'),req({params:{id:'11'},body:{status:'Rechazado'}}))).statusCode,409);const p=pool();const a=await setup(p);assert.equal((await invoke(a.route('post','/api/driver/trips/:id/checklist'),req())).statusCode,201);assert.ok(p.calls.some(x=>x.sql.startsWith('insert into vehicle_checklists')))});
test('fallo de alerta revierte cierre',async()=>{const p=pool({fail:"insert into alerts"});const a=await setup(p);const r=await invoke(a.route('patch','/api/driver/checklists/:id'),req({params:{id:'11'},body:{status:'Rechazado'}}));assert.equal(r.statusCode,400);assert.equal(p.calls.at(-1).sql,'ROLLBACK')});
