const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {registerOperationsRoutes}=require('../operations-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});routes.route=(method,path)=>routes.find(r=>r.method===method&&r.path===path);return routes}
function response(){return {statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,req){const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
function pool(trip){const calls=[];return {calls,async query(sql,values=[]){calls.push({sql,values});if(sql.includes('from trips'))return {rowCount:trip?1:0,rows:trip?[trip]:[]};if(sql.startsWith('insert into telemetry'))return {rowCount:1,rows:[{id:90,truck_id:trip.truck_id,trip_id:trip.id,lat:values[2],lng:values[3],speed_kmh:values[4],km:values[5],recorded_at:values[6]}]};throw Error(`unexpected ${sql}`)}}}
const user={role_code:'driver',company_id:10,driver_id:4};
test('callback GPS de una generación anterior queda invalidada',()=>{const js=fs.readFileSync(path.join(__dirname,'..','public','driver.js'),'utf8');assert.match(js,/gpsGeneration\+\+/);assert.match(js,/generation!==gpsGeneration\|\|gpsTripId!==trip\.id/);assert.match(js,/clearWatch\(gpsWatch\)/);assert.match(js,/now-gpsLastSent<10000/)});
test('driver GPS deriva camión, aplica scope y permite En tránsito/Detenido',async()=>{for(const status of ['En tránsito','Detenido']){const p=pool({id:7,company_id:10,driver_id:4,truck_id:31,status});const a=app();registerOperationsRoutes(a,p);const res=await invoke(a.route('post','/api/driver/trips/:id/positions'),{user,params:{id:'7'},body:{lat:-33.45,lng:-70.66,truck_id:999,company_id:999,driver_id:999}});assert.equal(res.statusCode,201);const insert=p.calls.find(c=>c.sql.startsWith('insert into telemetry'));assert.deepEqual(insert.values.slice(0,2),[31,7])}});
test('driver GPS rechaza viaje ajeno, identidad inválida y estados no capturables',async()=>{for(const trip of [null,{id:7,company_id:10,driver_id:4,truck_id:31,status:'Asignado'},{id:7,company_id:10,driver_id:4,truck_id:31,status:'Completado'}]){const p=pool(trip);const a=app();registerOperationsRoutes(a,p);const res=await invoke(a.route('post','/api/driver/trips/:id/positions'),{user,params:{id:'7'},body:{lat:0,lng:0}});assert.equal(res.statusCode,trip&&trip.status!=='Asignado'&&trip.status!=='Completado'?201:trip?409:404)}});
test('driver GPS exige rol y asociación',async()=>{const p=pool({id:7,company_id:10,driver_id:4,truck_id:31,status:'En tránsito'});const a=app();registerOperationsRoutes(a,p);for(const u of [{role_code:'driver',company_id:10,driver_id:null},{role_code:'operations',company_id:10,driver_id:4},{role_code:'admin',company_id:null,driver_id:null}])assert.equal((await invoke(a.route('post','/api/driver/trips/:id/positions'),{user:u,params:{id:'7'},body:{lat:0,lng:0}})).statusCode,403)});
test('driver GPS valida coordenadas velocidad y timestamp',async()=>{const p=pool({id:7,company_id:10,driver_id:4,truck_id:31,status:'En tránsito'});const a=app();registerOperationsRoutes(a,p);const route=a.route('post','/api/driver/trips/:id/positions');for(const body of [{lat:91,lng:0},{lat:0,lng:0,speed_kmh:-1},{lat:0,lng:0,recorded_at:'bad'}])assert.equal((await invoke(route,{user,params:{id:'7'},body})).statusCode,400)});
