const test=require('node:test');
const assert=require('node:assert/strict');
const {registerOperationsRoutes}=require('../operations-api');
const {registerFleetRoutes}=require('../fleet-api');
function app(){const routes=[];for(const m of ['get','post','patch'])routes[m]=(p,...h)=>routes.push({method:m,path:p,handlers:h});routes.route=(m,p)=>routes.find(x=>x.method===m&&x.path===p);return routes}
function response(){return {statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,req){const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
const driver={id:8,role_code:'driver',company_id:10,driver_id:4};
function opPool({company=10,driver=4,fail=null,status='Pendiente'}={}){const calls=[];let checklistStatus=status;let committed=false;const trip={id:7,company_id:company,driver_id:driver,truck_id:3};const client={async query(sql,v=[]){calls.push({sql,v});if(fail&&sql.includes(fail))throw Error('forced');if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK'){if(sql==='COMMIT')committed=true;if(sql==='ROLLBACK'){committed=false;checklistStatus=status}return {rows:[],rowCount:0}}if(sql.includes('from trips'))return {rows:Number(v[1])===company&&Number(v[2])===driver?[trip]:[],rowCount:Number(v[1])===company&&Number(v[2])===driver?1:0};if(sql.includes('from vehicle_checklists where trip_id'))return {rows:[{id:11,trip_id:7,company_id:company,driver_id:driver,truck_id:3,status:checklistStatus,items:[],observations:null}],rowCount:1};if(sql.includes('from vehicle_checklists vc join trips'))return {rows:Number(v[1])===company&&Number(v[2])===driver?[{id:11,trip_id:7,company_id:company,driver_id:driver,trip_driver_id:driver,truck_id:3,status:checklistStatus,items:[],observations:null}]:[],rowCount:Number(v[1])===company&&Number(v[2])===driver?1:0};if(sql.startsWith('insert into vehicle_checklists'))return {rows:[{id:12,trip_id:7,driver_id:driver,truck_id:3,status:'Pendiente',items:[],observations:null}],rowCount:1};if(sql.startsWith('update vehicle_checklists')){checklistStatus=v[0];return {rows:[{id:11,trip_id:7,driver_id:driver,truck_id:3,status:checklistStatus,items:v[1],observations:v[2]}],rowCount:1};}if(sql.startsWith('insert into alerts'))return {rows:[{id:90,company_id:company,source_type:'checklist',source_id:11,condition_code:'checklist_rejected',resolved:false}],rowCount:1};if(sql.startsWith('insert into'))return {rows:[],rowCount:1};throw Error(sql)},release(){}};return {calls,get checklistStatus(){return checklistStatus},get committed(){return committed},async query(...a){return client.query(...a)},async connect(){return client}}}
function req(user=driver,extra={}){return {user,params:{id:'11'},body:{},query:{},...extra}}
async function opRoutes(p){const a=app();await registerOperationsRoutes(a,p);return a}
test('aislamiento diferenciado en GET, POST y PATCH',async()=>{for(const [label,u,expected] of [['A/Driver A',{...driver,company_id:10,driver_id:4},200],['A/Driver B',{...driver,company_id:10,driver_id:5},404],['B/Driver C',{...driver,company_id:20,driver_id:6},404]]){const p=opPool({company:10,driver:4});const a=await opRoutes(p);const altered={company_id:999,driver_id:999,truck_id:999};assert.equal((await invoke(a.route('get','/api/driver/trips/:id/checklist'),req(u,{params:{id:'7'}}))).statusCode,expected,label);assert.equal((await invoke(a.route('post','/api/driver/trips/:id/checklist'),req(u,{params:{id:'7'},body:altered}))).statusCode,expected===200?201:404,label);assert.equal((await invoke(a.route('patch','/api/driver/checklists/:id'),req(u,{params:{id:'11'},body:{...altered,status:'Aprobado'}}))).statusCode,expected,label)}});
test('rechazo revierte completamente si falla alerta, evento o auditoría',async()=>{for(const fail of ['insert into alerts','insert into trip_events','insert into audit_logs']){const p=opPool({fail});const a=await opRoutes(p);const r=await invoke(a.route('patch','/api/driver/checklists/:id'),req(driver,{body:{status:'Rechazado'}}));assert.equal(r.statusCode,400,fail);assert.equal(p.checklistStatus,'Pendiente',fail);assert.equal(p.committed,false,fail);assert.equal(p.calls.at(-1).sql,'ROLLBACK',fail)}});
test('alerta de rechazo conserva valores concretos y no duplica activa',async()=>{const p=opPool();const a=await opRoutes(p);const r=await invoke(a.route('patch','/api/driver/checklists/:id'),req(driver,{body:{status:'Rechazado'}}));assert.equal(r.statusCode,200);const alert=p.calls.find(x=>x.sql.startsWith('insert into alerts'));assert.deepEqual(alert.v,[10,'Checklist rechazado para el viaje 7',11]);assert.match(alert.sql,/checklist/);assert.match(alert.sql,/checklist_rejected/);const second=await invoke(a.route('patch','/api/driver/checklists/:id'),req(driver,{body:{status:'Rechazado'}}));assert.equal(second.statusCode,409);assert.equal(p.calls.filter(x=>x.sql.startsWith('insert into alerts')).length,1)});
function alertPool({fail=null}={}){const calls=[];const client={async query(sql,v=[]){calls.push({sql,v});if(fail&&sql.startsWith(fail))throw Error('forced');if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return {rows:[],rowCount:0};if(sql.includes('from alerts a'))return {rows:[{id:90,company_id:10,source_type:'checklist',source_id:11,condition_code:'checklist_rejected',resolved:false}],rowCount:1};if(sql.startsWith('update alerts'))return {rows:[{id:90,company_id:10,resolved:true,resolved_by:8,resolution_note:'Gestionada',resolved_at:'2026-08-25T00:00:00Z'}],rowCount:1};if(sql.startsWith('insert into audit_logs'))return {rows:[],rowCount:1};throw Error(sql)},release(){}};return {calls,async connect(){return client},async query(...a){return client.query(...a)}}}
test('resolución checklist exige permiso y motivo, registra responsable y audita',async()=>{const deniedApp=app();await registerFleetRoutes(deniedApp,alertPool());const noDriver={...driver,permissions:[]};assert.equal((await invoke(deniedApp.route('post','/api/fleet/alerts/:id/resolve'),req(noDriver,{body:{resolution_note:'x'}}))).statusCode,403);const a=app(),p=alertPool();await registerFleetRoutes(a,p);const r=await invoke(a.route('post','/api/fleet/alerts/:id/resolve'),{...req({id:8,role_code:'operations',company_id:10,permissions:['fleet.manage']}),body:{resolution_note:'Gestionada'}});assert.equal(r.statusCode,200);assert.equal(r.payload.resolved,true);assert.equal(r.payload.resolved_by,8);assert.ok(r.payload.resolved_at);assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')))});
test('resolución checklist revierte si falla actualización o auditoría',async()=>{for(const fail of ['update alerts','insert into audit_logs']){const a=app(),p=alertPool({fail});await registerFleetRoutes(a,p);const r=await invoke(a.route('post','/api/fleet/alerts/:id/resolve'),{...req({id:8,role_code:'operations',company_id:10,permissions:['fleet.manage']}),body:{resolution_note:'Gestionada'}});assert.equal(r.statusCode,400);assert.equal(p.calls.at(-1).sql,'ROLLBACK')}});
