const test=require('node:test');
const assert=require('node:assert/strict');
const {registerEconomicsRoutes}=require('../economics-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});return routes}
function response(){return {statusCode:200,headers:{},payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},type(v){this.headers.type=v;return this},set(k,v){this.headers[k]=v;return this},send(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,o={}){const req={user:{id:7,role_code:'operations',company_id:10,permissions:['economics.read']},params:{},query:{},body:{},...o};const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
const row={trip_id:1,trip_number:'V-1',company_id:10,client_id:2,truck_id:3,driver_id:4,status:'Completado',origin:'A',destination:'B',planned_departure:'2026-08-01',actual_departure:'2026-08-01T08:00:00Z',actual_arrival:'2026-08-01T10:00:00Z',revenue_clp:'10000',revenue_defined:true,revenue_includes_vat:false,direct_costs:'2000',approved_costs:null,reconciled_costs:'2000',loads_registered:'2',loads_delivered:'1',weight_kg:'500',volume_m3:'4',snapshot_distance_km:null,distance_km:'100',route_distance_km:null};
function route(pool){const a=app();registerEconomicsRoutes(a,pool);return a.find(r=>r.method==='get'&&r.path==='/api/economics/reports')}
function pool(rows=[row]){const calls=[];return {calls,async query(sql,values){calls.push({sql,values});return {rows:values[0]===10?rows:[],rowCount:values[0]===10?rows.length:0}}}}
test('genera reportes filtrados de viajes, economía y operación',async()=>{const p=pool(),r=route(p);let out=await invoke(r,{query:{report:'trips',from:'2026-08-01',to:'2026-08-31',client_id:'2',truck_id:'3',driver_id:'4',status:'Completado'}});assert.equal(out.statusCode,200);assert.equal(out.payload.rows[0].trip_id,1);assert.deepEqual(p.calls[0].values,[10,'2026-08-01','2026-08-31',2,3,4,'Completado']);out=await invoke(r,{query:{report:'economic'}});assert.equal(out.payload.rows[0].delta,8000);out=await invoke(r,{query:{report:'operational'}});assert.equal(out.payload.rows[0].loads_delivered,1);assert.equal(out.payload.rows[0].duration_minutes,120)});
test('exporta CSV y mantiene company scope/RBAC',async()=>{const p=pool(),r=route(p);let out=await invoke(r,{query:{report:'economic',format:'csv'}});assert.equal(out.statusCode,200);assert.equal(out.headers.type,'text/csv');assert.match(out.payload,/trip_id,trip_number,revenue_recognized/);out=await invoke(r,{user:{id:8,role_code:'operations',company_id:11,permissions:['economics.read']}});assert.equal(out.payload.count,0);out=await invoke(r,{user:{id:8,role_code:'viewer',company_id:10,permissions:[]}});assert.equal(out.statusCode,403)});
