const test=require('node:test');
const assert=require('node:assert/strict');
const {registerEconomicsRoutes}=require('../economics-api');

function fakeApp(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});routes.route=(method,path)=>{const r=routes.find(x=>x.method===method&&x.path===path);assert.ok(r,`Ruta no registrada: ${method} ${path}`);return r};return routes}
function response(){return {statusCode:200,payload:undefined,status(code){this.statusCode=code;return this},json(v){this.payload=v;return this},sendStatus(code){this.statusCode=code;return this}}}
async function invoke(route,o={}){const req={user:{id:7,role_code:'operations',company_id:10,permissions:['economics.read','economics.manage']},params:{id:'31'},query:{},body:{},ip:'127.0.0.1',...o};const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
function poolFor({trip=true,category={id:3,code:'toll',name:'Peajes',cost_group:'direct',active:true},failAt=null,versions=[{id:41,version_number:1}],costs=[]}={}){const calls=[];let releases=0;const client={async query(sql,values=[]){calls.push({source:'client',sql,values});if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return {rows:[],rowCount:0};if(sql.includes('from trips')&&sql.includes('for update'))return {rows:trip?[{id:31,company_id:10}]:[],rowCount:trip?1:0};if(sql.includes('economic_cost_categories')&&sql.includes('for share'))return {rows:category?[category]:[],rowCount:category?1:0};if(sql.startsWith('insert into trip_cost_items')){if(failAt==='item')throw Error('item');return {rows:[{id:51,company_id:10,trip_id:31,category_id:3,status:'active'}],rowCount:1}}if(sql.startsWith('insert into trip_cost_versions')){if(failAt==='version')throw Error('version');return {rows:[{id:42,trip_cost_item_id:51,version_number:versions.length+1,cost_basis:'observed',amount_clp:1000,status:'draft'}],rowCount:1}}if(sql.startsWith('select * from trip_cost_versions'))return {rows:[versions.at(-1)],rowCount:1};if(sql.startsWith('select i.*,c.code'))return {rows:[{id:51,company_id:10,trip_id:31,status:'active',category_code:'toll',category_name:'Peajes',cost_group:'direct'}],rowCount:1};if(sql.startsWith('update trip_cost_items')){if(failAt==='current')throw Error('current');return {rows:[{id:51,company_id:10,current_version_id:42,status:'active'}],rowCount:1}}if(sql.startsWith('insert into audit_logs')){if(failAt==='audit')throw Error('audit');return {rows:[],rowCount:1}}throw Error(`Unexpected ${sql}`)},release(){releases++}};return {calls,get releases(){return releases},async connect(){return client},async query(sql,values=[]){calls.push({source:'pool',sql,values});if(sql.startsWith('select id from trips'))return {rows:trip?[{id:31}]:[],rowCount:trip?1:0};if(sql.startsWith('select i.id'))return {rows:costs,rowCount:costs.length};throw Error(`Unexpected pool ${sql}`)}}}
const valid={category_code:'toll',amount_clp:1000,cost_basis:'observed',amount_includes_vat:false,support_status:'documented',effective_date:'2026-08-20',description:'Peaje ruta principal'};
function app(pool){const a=fakeApp();registerEconomicsRoutes(a,pool);return a}

test('crea costo scoped, item, versión vigente y auditoría en transacción',async()=>{const p=poolFor();const r=await invoke(app(p).route('post','/api/economics/trips/:id/costs'),{body:valid});assert.equal(r.statusCode,201);assert.equal(p.calls.filter(x=>x.source==='client').at(-1).sql,'COMMIT');assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_cost_items')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_cost_versions')));assert.ok(p.calls.some(x=>x.sql.startsWith('update trip_cost_items')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')));assert.equal(p.releases,1)});
test('rechaza viaje cross-company y categoria inexistente o indirecta',async()=>{let r=await invoke(app(poolFor({trip:false})).route('post','/api/economics/trips/:id/costs'),{body:valid});assert.equal(r.statusCode,404);r=await invoke(app(poolFor({category:null})).route('post','/api/economics/trips/:id/costs'),{body:valid});assert.equal(r.statusCode,400);r=await invoke(app(poolFor({category:{id:3,code:'commission',name:'Comisiones',cost_group:'indirect',active:true}})).route('post','/api/economics/trips/:id/costs'),{body:{...valid,category_code:'commission'}});assert.equal(r.statusCode,400)});
test('requiere manage y valida monto, IVA y undocumented',async()=>{const p=poolFor();const route=app(p).route('post','/api/economics/trips/:id/costs');for(const body of [{...valid,amount_clp:-1},{...valid,amount_clp:1.2},{...valid,amount_includes_vat:'false'},{...valid,support_status:'undocumented',justification:''}])assert.equal((await invoke(route,{body})).statusCode,400);assert.equal((await invoke(route,{user:{id:8,role_code:'viewer',company_id:10,permissions:['economics.read']},body:valid})).statusCode,403)});
test('rollback ante error de versión',async()=>{const p=poolFor({failAt:'version'});const r=await invoke(app(p).route('post','/api/economics/trips/:id/costs'),{body:valid});assert.equal(r.statusCode,500);assert.equal(p.calls.at(-1).sql,'ROLLBACK');assert.equal(p.releases,1)});
test('crea nueva versión y conserva la anterior',async()=>{const p=poolFor();const r=await invoke(app(p).route('post','/api/economics/costs/:id/versions'),{params:{id:'51'},body:{...valid,amount_clp:2000}});assert.equal(r.statusCode,201);const insert=p.calls.find(x=>x.sql.startsWith('insert into trip_cost_versions'));assert.equal(insert.values[2],2);assert.equal(insert.values[10],41);assert.ok(p.calls.some(x=>x.sql.startsWith('update trip_cost_items')));assert.equal(p.calls.at(-1).sql,'COMMIT')});
test('lectura de costos por viaje es scoped',async()=>{const row={id:51,company_id:10,trip_id:31,category_name:'Peajes',amount_clp:'1000',cost_basis:'observed',status:'draft'};const p=poolFor({costs:[row]});const r=await invoke(app(p).route('get','/api/economics/trips/:id/costs'));assert.equal(r.statusCode,200);assert.equal(r.payload[0].amount_clp,1000);assert.deepEqual(p.calls[0].values,['31',10])});
test('frontend contiene carga, formulario, POST de costos y error visible',()=>{const fs=require('fs');const source=fs.readFileSync(require('path').join(__dirname,'..','public','operations-ui.js'),'utf8');assert.match(source,/economics\/trips\/\$\{trip\.id\}\/costs/);assert.match(source,/id='economicCostForm'/);assert.match(source,/send\(`economics\/trips\/\$\{trip\.id\}\/costs`,'POST'/);assert.match(source,/economicCostError/);assert.match(source,/cost_basis/)});
