const test=require('node:test');
const assert=require('node:assert/strict');
const {registerEconomicsRoutes}=require('../economics-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});return routes}
function response(){return {statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,o={}){const req={user:{id:7,role_code:'operations',company_id:10,permissions:['economics.read']},params:{},query:{},body:{},...o};const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
const trip={id:1,company_id:10,client_id:2,truck_id:3,driver_id:4,status:'Completado',revenue_clp:'10000',revenue_defined:true,revenue_includes_vat:false,distance_km:'100',snapshot_distance_km:null,route_distance_km:null,recognized_costs:'2000',approved_costs:null,reconciled_costs:'2000',load_count:'2',weight_kg:'500',volume_m3:'4',delivered_count:'1'};
function pool(rows=[trip],company=10){const calls=[];return {calls,async query(sql,values=[]){calls.push({sql,values});if(sql.includes('with filtered'))return {rows:values[0]===company?rows:[],rowCount:values[0]===company?rows.length:0};if(sql.startsWith('select count(*)')&&sql.includes('vehicle_documents'))return {rows:[{active:'1',expired:'0',vehicle_count:'1',driver_count:'0'}],rowCount:1};if(sql.startsWith('select count(*)')&&sql.includes('status=\'Pendiente\''))return {rows:[{pending:'1',in_process:'0',completed:'2',cancelled:'0',overdue:'1'}],rowCount:1};if(sql.startsWith('select count(*)')&&sql.includes('resolved=false'))return {rows:[{open:'1',resolved:'2',open_critical:'1'}],rowCount:1};if(sql.startsWith('select count(*)')&&sql.includes('vehicle_checklists'))return {rows:[{approved:'1',pending:'0',rejected:'0'}],rowCount:1};if(sql.startsWith('select count(*)')&&sql.includes('from trucks'))return {rows:[{active:'2',available:'1',maintenance:'1'}],rowCount:1};if(sql.startsWith('select coalesce(sum(liters)'))return {rows:[{liters:'100',total_clp:'120000'}],rowCount:1};throw Error(`unexpected ${sql}`)}}}
function route(p){const a=app();registerEconomicsRoutes(a,p);return a.find(r=>r.method==='get'&&r.path==='/api/economics/kpis')}
test('calcula estados, cargas, ingreso, costos, delta y delta/km',async()=>{const r=await invoke(route(pool()));assert.equal(r.statusCode,200);assert.equal(r.payload.operations.trips_by_status.Completado,1);assert.equal(r.payload.operations.loads.registered,2);assert.equal(r.payload.operations.loads.delivered,1);assert.equal(r.payload.economics.recognized_revenue.amount,10000);assert.equal(r.payload.economics.recognized_costs.amount,2000);assert.equal(r.payload.economics.delta.reconciled,8000);assert.equal(r.payload.economics.delta_per_km.reconciled,80);assert.equal(r.payload.fuel_operational.total_clp,120000)});
test('aplica filtros y no expone otra empresa',async()=>{const p=pool();const r=await invoke(route(p),{query:{from:'2026-08-01',to:'2026-08-31',client_id:'2',truck_id:'3',driver_id:'4',status:'Completado'}});assert.equal(r.statusCode,200);assert.deepEqual(p.calls[0].values,[10,'2026-08-01','2026-08-31',2,3,4,'Completado']);const cross=await invoke(route(pool([],10)),{user:{id:8,role_code:'operations',company_id:11,permissions:['economics.read']}});assert.equal(cross.payload.operations.planned,0)});
test('admin exige company_id explícito y RBAC',async()=>{let r=await invoke(route(pool()),{user:{id:1,role_code:'admin',company_id:null,permissions:['economics.read']}});assert.equal(r.statusCode,400);r=await invoke(route(pool()),{user:{id:8,role_code:'viewer',company_id:10,permissions:[]}});assert.equal(r.statusCode,403)});
test('ingreso legacy y ausencia de costos no se convierten en ingreso o delta reconocidos',async()=>{const legacy={...trip,revenue_defined:false,revenue_clp:'150000',recognized_costs:'0',approved_costs:null,reconciled_costs:null};const r=await invoke(route(pool([legacy])));assert.equal(r.payload.economics.recognized_revenue.amount,0);assert.equal(r.payload.economics.recognized_revenue.trips,0);assert.equal(r.payload.economics.delta.missing_data,1);assert.equal(r.payload.economics.delta.provisional,null||0)});
test('dashboard ejecutivo consume el endpoint de KPIs y distingue estados económicos',()=>{const fs=require('fs'),path=require('path');const source=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');assert.match(source,/get\("economics\/kpis"\)/);assert.match(source,/Delta provisional/);assert.match(source,/Delta reconciliado/);assert.match(source,/Missing data/);assert.match(source,/distancia oficial planificada/)});
test('dashboard KPI ofrece filtros y los envía al endpoint existente',()=>{const fs=require('fs'),path=require('path');const source=fs.readFileSync(path.join(__dirname,'..','public','app.js'),'utf8');assert.match(source,/kpiFrom/);assert.match(source,/kpiTo/);assert.match(source,/kpiClient/);assert.match(source,/kpiTruck/);assert.match(source,/kpiDriver/);assert.match(source,/kpiStatus/);assert.match(source,/economics\/kpis\?\$\{params\}/);assert.match(source,/applyKpiFilters/)});
