const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('crypto');const {registerEconomicsRoutes}=require('../economics-api');
const reauthHash=`scrypt$bad$${crypto.scryptSync('x','bad',64,{N:16384,r:8,p:1}).toString('hex')}`;
function app(){const r=[];for(const m of ['get','post','patch'])r[m]=(p,...h)=>r.push({method:m,path:p,handlers:h});r.route=(m,p)=>{const x=r.filter(y=>y.method===m&&y.path===p);assert.ok(x.length);return {method:m,path:p,handlers:x.flatMap(y=>y.handlers)}};return r}
function res(){return{statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function invoke(route,o={}){const req={user:{id:7,role_code:'manager',company_id:10,permissions:['economics.read','economics.manage','economics.approve']},params:{id:'9'},query:{},body:{},ip:'127.0.0.1',...o};const out=res();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,out,next)};await next();return out}
function pool({status='draft',fail=false,trip=true}={}){const calls=[];let releases=0;const client={async query(sql,v=[]){calls.push({source:'client',sql,v});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('from trips'))return{rows:trip?[{id:31,company_id:10}]:[],rowCount:trip?1:0};if(sql.includes('trip_cost_versions')&&sql.includes('join trip_cost_items'))return{rows:status?[{id:41,status,authorization_request_id:null,trip_id:31}]:[],rowCount:status?1:0};if(sql.startsWith('select id,status,authorization_request_id'))return{rows:[{id:41,status:'pending_approval',authorization_request_id:90}],rowCount:1};if(sql.startsWith('insert into economic_authorization_requests'))return{rows:[{id:90,company_id:10,trip_id:31,request_type:'cost_version',requested_by:7,status:'pending',cost_version_id:41}],rowCount:1};if(sql.startsWith('update trip_cost_versions')){if(fail)throw Error('update');return{rows:[],rowCount:1}}if(sql.includes('from economic_authorization_requests'))return{rows:[{id:90,company_id:10,trip_id:31,requested_by:7,status:'pending',cost_version_id:41}],rowCount:1};if(sql.startsWith('update economic_authorization_requests')){if(fail)throw Error('resolve');return{rows:[{id:90,status:'approved',resolved_by:8}],rowCount:1}}if(sql.startsWith('insert into audit_logs')){if(fail)throw Error('audit');return{rows:[],rowCount:1}}throw Error(sql)},release(){releases++}};return{calls,get releases(){return releases},async connect(){return client},async query(sql,v=[]){calls.push({source:'pool',sql,v});if(sql.startsWith('select password_hash'))return{rows:[{password_hash:reauthHash}],rowCount:1};if(sql.includes('from economic_authorization_requests'))return{rows:[],rowCount:0};throw Error(sql)}}}
const valid={trip_id:31,request_type:'cost_version',cost_version_id:41,reason:'Cambio económico solicitado'};
test('creación company-scoped registra solicitante, versión y auditoría',async()=>{const p=pool();const r=await invoke((()=>{const a=app();registerEconomicsRoutes(a,p);return a})().route('post','/api/economics/authorizations'),{body:valid});assert.equal(r.statusCode,201);assert.ok(p.calls.some(x=>x.sql.startsWith('insert into economic_authorization_requests')));assert.ok(p.calls.some(x=>x.sql.startsWith('update trip_cost_versions')));assert.equal(p.releases,1)});
test('motivo, permiso, cross-company y versión inválida son rechazados',async()=>{const a=app(),p=pool();registerEconomicsRoutes(a,p);assert.equal((await invoke(a.route('post','/api/economics/authorizations'),{body:{...valid,reason:''}})).statusCode,400);assert.equal((await invoke(a.route('post','/api/economics/authorizations'),{user:{id:4,role_code:'operations',company_id:10,permissions:[]},body:valid})).statusCode,403);const p0=pool({trip:false}),a0=app();registerEconomicsRoutes(a0,p0);assert.equal((await invoke(a0.route('post','/api/economics/authorizations'),{body:valid})).statusCode,404);const p2=pool({status:'superseded'}),a2=app();registerEconomicsRoutes(a2,p2);assert.equal((await invoke(a2.route('post','/api/economics/authorizations'),{body:valid})).statusCode,409)});
test('consulta requiere lectura y mantiene aislamiento',async()=>{const a=app(),p=pool();registerEconomicsRoutes(a,p);assert.equal((await invoke(a.route('get','/api/economics/authorizations/:id'),{params:{id:'90'}})).statusCode,404);assert.equal((await invoke(a.route('get','/api/economics/authorizations/:id'),{user:{id:4,role_code:'operations',company_id:10,permissions:[]},params:{id:'90'}})).statusCode,403)});
test('resolución exige reautenticación, motivo, autorizador distinto y permiso approve',async()=>{const a=app(),p=pool();registerEconomicsRoutes(a,p);const route=a.route('post','/api/economics/authorizations/:id/approve');assert.equal((await invoke(route,{body:{reason:'',password:'x'}})).statusCode,400);assert.equal((await invoke(route,{user:{id:7,role_code:'manager',company_id:10,permissions:['economics.approve']},body:{reason:'ok',password:'x'}})).statusCode,403);assert.equal((await invoke(route,{user:{id:8,role_code:'manager',company_id:10,permissions:['economics.approve']},body:{reason:'',password:'x'}})).statusCode,400)});
test('rollback ante error de resolución',async()=>{const a=app(),p=pool({fail:true});registerEconomicsRoutes(a,p);const r=await invoke(a.route('post','/api/economics/authorizations/:id/approve'),{user:{id:8,role_code:'manager',company_id:10,permissions:['economics.approve']},body:{reason:'Aprobado',password:'x'}});assert.equal(r.statusCode,500);assert.equal(p.calls.at(-1).sql,'ROLLBACK');assert.equal(p.releases,1)});
test('rechazo usa endpoint separado y exige economics.approve',async()=>{const a=app(),p=pool();registerEconomicsRoutes(a,p);assert.equal((await invoke(a.route('post','/api/economics/authorizations/:id/reject'),{user:{id:8,role_code:'operations',company_id:10,permissions:['economics.manage']},body:{reason:'No aprobado',password:'x'}})).statusCode,403)});
