const test=require('node:test');
const assert=require('node:assert/strict');
const {registerEconomicsRoutes}=require('../economics-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});return routes}
function res(){return {statusCode:200,payload:null,status(c){this.statusCode=c;return this},json(v){this.payload=v;return this},sendStatus(c){this.statusCode=c;return this}}}
async function call(route,{user={id:7,role_code:'operations',company_id:10,permissions:['economics.read']},body={},query={}}={}){const req={user,params:{id:'31'},body,query};const out=res();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,out,next)};await next();return out}
function pool(rows){return {async query(sql,values){if(sql.includes('from trips')){const scoped=values[1]===10;return {rows:scoped?rows:[],rowCount:scoped?rows.length:0};}throw Error(`unexpected ${sql}`)}}}
function route(rows){const routes=app();registerEconomicsRoutes(routes,pool(rows));return routes.find(r=>r.method==='get'&&r.path==='/api/economics/trips/:id/delta')}
const base={trip_id:31,company_id:10,revenue_clp:10000,revenue_defined:true,revenue_includes_vat:false,snapshot_distance_km:null,trip_distance_km:'100',route_distance_km:'80'};
const cost=(id,status,basis='observed',extra={})=>({...base,cost_item_id:id,item_status:'active',current_version_id:id,category_code:'toll',category_name:'Peajes',cost_group:'direct',version_id:id,version_number:1,amount_clp:'2000',cost_basis:basis,version_status:status,...extra});
test('calcula provisional, reconciliado, mezcla y delta/km usando current_version_id',async()=>{let r=await call(route([cost(1,'approved')]));assert.equal(r.payload.delta_status,'provisional');assert.equal(r.payload.delta,8000);assert.equal(r.payload.delta_per_km,80);r=await call(route([cost(1,'reconciled')]));assert.equal(r.payload.delta_status,'reconciled');r=await call(route([cost(1,'reconciled'),cost(2,'approved')]));assert.equal(r.payload.delta_status,'provisional');assert.equal(r.payload.total_recognized_costs,4000)});
test('missing data, exclusiones, distancia y permisos',async()=>{let r=await call(route([{...base,revenue_defined:false,cost_item_id:null}]));assert.equal(r.payload.delta_status,'missing_data');r=await call(route([{...cost(1,'draft'),amount_clp:'9000'},cost(2,'approved','indirect'),cost(3,'voided'),cost(4,'pending_approval')]));assert.equal(r.payload.delta_status,'missing_data');assert.equal(r.payload.delta,null);assert.equal(r.payload.costs.length,0);assert.equal(r.payload.delta_per_km,null);r=await call(route([{...cost(1,'reconciled'),snapshot_distance_km:'120',trip_distance_km:'100',route_distance_km:'80'}]));assert.equal(r.payload.distance_source,'trip_route_snapshot');r=await call(route([{...cost(1,'reconciled'),snapshot_distance_km:null,trip_distance_km:null,route_distance_km:null}]));assert.equal(r.payload.delta_per_km,null);r=await call(route([cost(1,'approved')]),{user:{id:8,role_code:'viewer',company_id:10,permissions:[]}});assert.equal(r.statusCode,403);r=await call(route([cost(1,'approved')]),{user:{id:1,role_code:'admin',company_id:null,permissions:['economics.read']}});assert.equal(r.statusCode,400);r=await call(route([cost(1,'approved')]),{user:{id:1,role_code:'admin',company_id:null,permissions:['economics.read']},query:{company_id:11}});assert.equal(r.statusCode,404)});
test('ingreso declarado pero nulo queda en missing_data y sin delta',async()=>{const r=await call(route([{...cost(1,'reconciled'),revenue_defined:true,revenue_clp:null}]));assert.equal(r.payload.delta_status,'missing_data');assert.equal(r.payload.delta,null);assert.equal(r.payload.delta_per_km,null);assert.equal(r.payload.revenue.amount,null)});
test('los tres caminos consumen la regla operacional canónica',()=>{const fs=require('fs'),source=fs.readFileSync(require.resolve('../economics-api'),'utf8');assert.ok(source.match(/operationalDelta\(/g).length>=3);assert.match(source,/const finalCalculation=operationalDelta/);assert.match(source,/calculation=operationalDelta/)});
