const test=require('node:test');
const assert=require('node:assert/strict');
const {registerEconomicsRoutes}=require('../economics-api');

function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});return routes}
function response(){return {statusCode:200,payload:undefined,status(code){this.statusCode=code;return this},json(v){this.payload=v;return this},sendStatus(code){this.statusCode=code;return this}}}
async function invoke(route,body={},user={id:7,role_code:'operations',company_id:10,permissions:['economics.manage']}){const req={user,params:{id:'51'},body,ip:'127.0.0.1'};const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
function pool({fail=false}={}){const calls=[];const client={async query(sql,values=[]){calls.push({sql,values});if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return {rows:[],rowCount:0};if(sql.includes('from trip_cost_items')&&sql.includes('for update'))return {rows:[{id:51,company_id:10,trip_id:31,current_version_id:41,status:'active',category_code:'toll',category_name:'Peajes',cost_group:'direct'}],rowCount:1};if(sql.startsWith('select * from trip_cost_versions'))return {rows:[{id:41,trip_cost_item_id:51,company_id:10,version_number:2,cost_basis:'observed',amount_clp:1000,amount_includes_vat:false,support_status:'documented',justification:null,description:'Peaje',effective_date:'2026-08-20',status:'approved'}],rowCount:1};if(sql.startsWith('insert into trip_cost_versions')){if(fail)throw Error('insert');return {rows:[{id:42,trip_cost_item_id:51,version_number:3,cost_basis:'observed',amount_clp:1000,status:'reconciled'}],rowCount:1}}if(sql.startsWith('update trip_cost_items'))return {rows:[{id:51,current_version_id:42,status:'reconciled'}],rowCount:1};if(sql.startsWith('insert into audit_logs'))return {rows:[],rowCount:1};throw Error(`Unexpected ${sql}`)},release(){}};return {calls,async connect(){return client}}}

test('concilia explícitamente una versión aprobada creando una nueva versión y auditando',async()=>{const p=pool();const routes=app();registerEconomicsRoutes(routes,p);const r=await invoke(routes.find(x=>x.method==='post'&&x.path==='/api/economics/costs/:id/reconcile'),{reason:'Factura revisada'});assert.equal(r.statusCode,201);assert.equal(p.calls.at(-1).sql,'COMMIT');assert.ok(p.calls.some(x=>x.sql.startsWith('insert into trip_cost_versions')));assert.ok(p.calls.some(x=>x.sql.startsWith('insert into audit_logs')));assert.equal(p.calls.find(x=>x.sql.startsWith('insert into trip_cost_versions')).values[2],3)});
test('exige motivo, permiso y company scope',async()=>{const p=pool();const routes=app();registerEconomicsRoutes(routes,p);const route=routes.find(x=>x.method==='post'&&x.path==='/api/economics/costs/:id/reconcile');assert.equal((await invoke(route,{})).statusCode,400);assert.equal((await invoke(route,{reason:'x'},{id:8,role_code:'viewer',company_id:10,permissions:[]})).statusCode,403);assert.equal((await invoke(route,{reason:'x'},{id:8,role_code:'operations',company_id:11,permissions:['economics.manage']})).statusCode,404)});
test('rollback ante error al crear la versión conciliada',async()=>{const p=pool({fail:true});const routes=app();registerEconomicsRoutes(routes,p);const r=await invoke(routes.find(x=>x.method==='post'&&x.path==='/api/economics/costs/:id/reconcile'),{reason:'revisión'});assert.equal(r.statusCode,500);assert.equal(p.calls.at(-1).sql,'ROLLBACK')});
