const test=require('node:test');
const assert=require('node:assert/strict');
const {registerGeographyRoutes}=require('../geography-api');

function app(){const routes=[];routes.post=(path,...handlers)=>routes.push({path,handlers});routes.route=path=>routes.find(route=>route.path===path);return routes}
function response(){return {statusCode:200,payload:undefined,status(code){this.statusCode=code;return this},json(value){this.payload=value;return this}}}
const normalized={name:'Terminal',address:'Terminal, Santiago',commune:'Santiago',region:'RM',lat:-33.4,lng:-70.6,source:'test',external_id:'x',normalized_at:'2026-08-01T00:00:00.000Z'};
function poolFor(companyId){const calls=[];const client={async query(sql,values=[]){calls.push({sql,values});if(sql.startsWith('insert into operational_locations'))return {rows:[{id:1,company_id:companyId}]};return {rows:[]}},release(){}};return {calls,async connect(){return client}}}
async function invoke(route,user,body={},query={}){const req={user,body,query,ip:'127.0.0.1'},res=response();let index=0;const next=async()=>{const handler=route.handlers[index++];if(handler)return handler(req,res,next)};await next();return {req,res}}
function modern(companyId,extra={}){return {id:5,actor_type:'company',scope:'company',company_id:companyId,membership_id:11,platform_membership_id:null,role_code:'operations',permissions:['trips.manage'],...extra}}
function register(pool){const target=app();registerGeographyRoutes(target,pool,{async geocode(){return normalized}});return target.route('/api/geography/locations')}

test('geography usa la membership moderna aunque users.company_id legacy difiera',async()=>{const pool=poolFor(10),result=await invoke(register(pool),modern(10),{query:'Terminal',company_id:20});assert.equal(result.res.statusCode,201);assert.equal(pool.calls.find(c=>c.sql.startsWith('insert into operational_locations')).values[0],10)})
test('geography funciona con company_id legacy NULL',async()=>{const pool=poolFor(10),result=await invoke(register(pool),modern(10),{query:'Terminal',company_id:null});assert.equal(result.res.statusCode,201);assert.equal(pool.calls.find(c=>c.sql.startsWith('insert into operational_locations')).values[0],10)})
test('membership múltiple sin contexto rechaza sin seleccionar empresa',async()=>{const pool={async connect(){throw new Error('no debe conectar')}};const result=await invoke(register(pool),{...modern(null),actor_type:'unresolved',scope:null,company_id:null,membership_id:null},{query:'Terminal',company_id:10});assert.equal(result.res.statusCode,400)})
test('platform sin contexto rechaza aunque body y query incluyan company_id',async()=>{const pool={async connect(){throw new Error('no debe conectar')}};const result=await invoke(register(pool),{...modern(null),actor_type:'platform',scope:'platform',membership_id:null,platform_membership_id:7},{query:'Terminal',company_id:10},{company_id:10});assert.equal(result.res.statusCode,400)})
test('company_id del body y query no cambian el scope moderno',async()=>{const pool=poolFor(10),result=await invoke(register(pool),modern(10),{query:'Terminal',company_id:20},{company_id:20});assert.equal(result.res.statusCode,201);assert.equal(pool.calls.find(c=>c.sql.startsWith('insert into operational_locations')).values[0],10)})
test('rol legacy admin en actor moderno no activa bypass transversal',async()=>{const pool=poolFor(10),result=await invoke(register(pool),modern(10,{role_code:'admin'}),{query:'Terminal',company_id:20});assert.equal(result.res.statusCode,201);assert.equal(pool.calls.find(c=>c.sql.startsWith('insert into operational_locations')).values[0],10)})
test('actor legacy conserva la compatibilidad de company_id explícito',async()=>{const pool=poolFor(20),result=await invoke(register(pool),{id:5,actor_type:'legacy',scope:'company',company_id:10,role_code:'admin',permissions:['trips.manage']},{query:'Terminal',company_id:20});assert.equal(result.res.statusCode,201);assert.equal(pool.calls.find(c=>c.sql.startsWith('insert into operational_locations')).values[0],20)})
