const test=require('node:test');
const assert=require('node:assert/strict');
const {registerFleetRoutes}=require('../fleet-api');

function fakeApp(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});routes.route=(method,path)=>{const route=routes.find(item=>item.method===method&&item.path===path);assert.ok(route,`Ruta no registrada: ${method} ${path}`);return route};return routes}
function response(){return {statusCode:200,payload:undefined,status(code){this.statusCode=code;return this},json(value){this.payload=value;return this},sendStatus(code){this.statusCode=code;return this}}}
async function invoke(route,overrides={}){const req={user:{id:7,role_code:'maintenance',company_id:10,permissions:['maintenance.manage']},body:{},query:{},params:{},ip:'127.0.0.1',...overrides};const res=response();let index=0;const next=async()=>{const handler=route.handlers[index++];if(handler)return handler(req,res,next)};await next();return res}
function mockPool(resolver){const calls=[];let releases=0;const client={async query(sql,values=[]){calls.push({sql,values});return resolver(sql,values,calls)},release(){releases++}};return {calls,get releases(){return releases},async connect(){return client},async query(sql,values=[]){calls.push({sql,values});return resolver(sql,values,calls)}}}
async function maintenanceApp(pool){const app=fakeApp();await registerFleetRoutes(app,pool);return app}
const validBody={truck_id:3,item:'Cambio de aceite',maintenance_type:'Preventiva',status:'Pendiente',due:'2026-09-01',performed_at:'2026-08-19',odometer_km:10500,workshop:'Taller Norte',notes:'Control',parts_description:'Filtro y aceite',parts_cost_clp:90000,labor_cost_clp:30000,next_due_date:'2027-02-19',next_due_odometer_km:20500};

test('mantención crea registro canónico, calcula total y audita antes de COMMIT',async()=>{
 const created={id:41,company_id:10,truck:'ABCD12',truck_id:3,...validBody,cost_clp:120000};
 const pool=mockPool(async(sql,values)=>{if(sql==='BEGIN'||sql==='COMMIT')return {rows:[],rowCount:0};if(sql.startsWith('select id,company_id,patente from trucks')){assert.deepEqual(values,[3,10]);return {rows:[{id:3,company_id:10,patente:'ABCD12'}],rowCount:1}}if(sql.startsWith('insert into maintenance')){assert.equal(values[5],120000);assert.equal(values[13],90000);assert.equal(values[14],30000);return {rows:[created],rowCount:1}}if(sql.startsWith('insert into audit_logs')){assert.equal(values[0],10);assert.equal(values[1],7);assert.equal(values[2],'create');assert.equal(values[3],'maintenance');assert.equal(values[4],'41');assert.equal(values[6].cost_clp,120000);return {rows:[],rowCount:1}}throw new Error(`Consulta inesperada: ${sql}`)});
 const app=await maintenanceApp(pool);const res=await invoke(app.route('post','/api/fleet/maintenance'),{body:{...validBody,cost_clp:1}});
 assert.equal(res.statusCode,201);assert.equal(res.payload.cost_clp,120000);assert.deepEqual(pool.calls.map(c=>c.sql==='BEGIN'||c.sql==='COMMIT'?c.sql:c.sql.startsWith('select')?'TRUCK':c.sql.startsWith('insert into maintenance')?'INSERT':'AUDIT'),['BEGIN','TRUCK','INSERT','AUDIT','COMMIT']);assert.equal(pool.releases,1);
});

test('mantención rechaza camión inexistente o cross-company sin insertar ni auditar',async()=>{
 const pool=mockPool(async sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[],rowCount:0};if(sql.startsWith('select id,company_id,patente from trucks'))return {rows:[],rowCount:0};throw new Error(`Consulta inesperada: ${sql}`)});
 const app=await maintenanceApp(pool);const res=await invoke(app.route('post','/api/fleet/maintenance'),{body:validBody});assert.equal(res.statusCode,404);assert.equal(pool.calls.some(c=>c.sql.startsWith('insert into maintenance')),false);assert.equal(pool.calls.some(c=>c.sql.startsWith('insert into audit_logs')),false);assert.equal(pool.calls.some(c=>c.sql==='COMMIT'),false);assert.equal(pool.releases,1);
});

test('mantención valida tipo, estado, fechas, odómetros y costos antes de conectar',async()=>{
 const pool={async connect(){throw new Error('No debe conectar')},async query(){throw new Error('No debe consultar')}};const app=await maintenanceApp(pool);const route=app.route('post','/api/fleet/maintenance');
 const cases=[[{...validBody,maintenance_type:'Predictiva'},'maintenance_type no válido'],[{...validBody,status:'Programada'},'status no válido'],[{...validBody,due:'2026-02-30'},'Fecha no válida'],[{...validBody,odometer_km:-1},'odometer_km no válido'],[{...validBody,next_due_odometer_km:-1},'next_due_odometer_km no válido'],[{...validBody,parts_cost_clp:-1},'costos no válidos'],[{...validBody,labor_cost_clp:'x'},'costos no válidos']];
 for(const [body,error] of cases){const res=await invoke(route,{body});assert.equal(res.statusCode,400);assert.deepEqual(res.payload,{error})}
});

test('mantención revierte por fallo de INSERT o auditoría y libera una vez',async()=>{
 for(const failure of ['insert','audit']){const pool=mockPool(async sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[],rowCount:0};if(sql.startsWith('select id,company_id,patente from trucks'))return {rows:[{id:3,company_id:10,patente:'ABCD12'}],rowCount:1};if(sql.startsWith('insert into maintenance')){if(failure==='insert')throw new Error('insert failed');return {rows:[{id:41,company_id:10,truck_id:3}],rowCount:1}}if(sql.startsWith('insert into audit_logs'))throw new Error('audit failed');throw new Error(`Consulta inesperada: ${sql}`)});const app=await maintenanceApp(pool);const res=await invoke(app.route('post','/api/fleet/maintenance'),{body:validBody});assert.equal(res.statusCode,400);assert.equal(pool.calls.at(-1).sql,'ROLLBACK');assert.equal(pool.calls.some(c=>c.sql==='COMMIT'),false);assert.equal(pool.releases,1)}
});

test('PATCH bloquea, conserva BEFORE, completa y audita AFTER sin modificar trucks.status',async()=>{
 const before={id:41,company_id:10,truck:'ABCD12',truck_id:3,item:'Aceite',maintenance_type:'Preventiva',status:'En proceso',due:'2026-09-01',performed_at:null,odometer_km:10000,parts_cost_clp:'50000',labor_cost_clp:'20000',cost_clp:'70000',truck_patente:'ABCD12'};
 const after={...before,status:'Completada',performed_at:'2026-08-19',odometer_km:10500,parts_cost_clp:'90000',labor_cost_clp:'30000',cost_clp:'120000'};
 const pool=mockPool(async(sql,values)=>{if(sql==='BEGIN'||sql==='COMMIT')return {rows:[],rowCount:0};if(sql.includes('from maintenance m')&&sql.includes('for update of m')){assert.match(sql,/m\.company_id=\$2/);return {rows:[before],rowCount:1}}if(sql.startsWith('select id,company_id,patente from trucks'))return {rows:[{id:3,company_id:10,patente:'ABCD12'}],rowCount:1};if(sql.startsWith('update maintenance')){assert.equal(values[4],120000);return {rows:[after],rowCount:1}}if(sql.startsWith('insert into audit_logs')){assert.equal(values[2],'update');assert.deepEqual(values[5],before);assert.equal(values[6].status,'Completada');return {rows:[],rowCount:1}}throw new Error(`Consulta inesperada: ${sql}`)});
 const app=await maintenanceApp(pool);const res=await invoke(app.route('patch','/api/fleet/maintenance/:id'),{params:{id:'41'},body:{status:'Completada',performed_at:'2026-08-19',odometer_km:10500,parts_cost_clp:90000,labor_cost_clp:30000}});assert.equal(res.statusCode,200);assert.equal(res.payload.status,'Completada');assert.deepEqual(pool.calls.map(c=>c.sql==='BEGIN'||c.sql==='COMMIT'?c.sql:c.sql.includes('from maintenance m')?'BEFORE':c.sql.startsWith('select id')?'TRUCK':c.sql.startsWith('update maintenance')?'UPDATE':'AUDIT'),['BEGIN','BEFORE','TRUCK','UPDATE','AUDIT','COMMIT']);assert.equal(pool.calls.some(c=>/update trucks/i.test(c.sql)),false);assert.equal(pool.releases,1);
});

test('PATCH devuelve 404 para mantención inexistente o fuera de scope sin mutar',async()=>{
 const pool=mockPool(async sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[],rowCount:0};if(sql.includes('from maintenance m')&&sql.includes('for update of m'))return {rows:[],rowCount:0};throw new Error(`Consulta inesperada: ${sql}`)});const app=await maintenanceApp(pool);const res=await invoke(app.route('patch','/api/fleet/maintenance/:id'),{params:{id:'99'},body:{status:'Completada'}});assert.equal(res.statusCode,404);assert.equal(pool.calls.some(c=>c.sql.startsWith('update maintenance')),false);assert.equal(pool.calls.some(c=>c.sql.startsWith('insert into audit_logs')),false);assert.equal(pool.calls.some(c=>c.sql==='COMMIT'),false);assert.equal(pool.releases,1);
});

test('PATCH revierte por fallo de UPDATE o auditoría sin COMMIT',async()=>{
 const before={id:41,company_id:10,truck_id:3,truck:'ABCD12',item:'Aceite',maintenance_type:'Preventiva',status:'Pendiente',parts_cost_clp:0,labor_cost_clp:0};
 for(const failure of ['update','audit']){const pool=mockPool(async sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[],rowCount:0};if(sql.includes('from maintenance m')&&sql.includes('for update of m'))return {rows:[before],rowCount:1};if(sql.startsWith('select id,company_id,patente from trucks'))return {rows:[{id:3,company_id:10,patente:'ABCD12'}],rowCount:1};if(sql.startsWith('update maintenance')){if(failure==='update')throw new Error('update failed');return {rows:[before],rowCount:1}}if(sql.startsWith('insert into audit_logs'))throw new Error('audit failed');throw new Error(`Consulta inesperada: ${sql}`)});const app=await maintenanceApp(pool);const res=await invoke(app.route('patch','/api/fleet/maintenance/:id'),{params:{id:'41'},body:{notes:'corregida'}});assert.equal(res.statusCode,400);assert.equal(pool.calls.at(-1).sql,'ROLLBACK');assert.equal(pool.calls.some(c=>c.sql==='COMMIT'),false);assert.equal(pool.releases,1)}
});

test('PATCH conserva costo legacy sin desglose cuando solo corrige datos administrativos',async()=>{
 const before={id:8,company_id:10,truck_id:3,truck:'ABCD12',item:'Servicio legacy',maintenance_type:'Preventiva',status:'Pendiente',cost_clp:'185000',parts_cost_clp:'0',labor_cost_clp:'0'};let updateValues;
 const pool=mockPool(async(sql,values)=>{if(sql==='BEGIN'||sql==='COMMIT')return {rows:[],rowCount:0};if(sql.includes('from maintenance m')&&sql.includes('for update of m'))return {rows:[before],rowCount:1};if(sql.startsWith('select id,company_id,patente from trucks'))return {rows:[{id:3,company_id:10,patente:'ABCD12'}],rowCount:1};if(sql.startsWith('update maintenance')){updateValues=values;return {rows:[{...before,notes:'corregida'}],rowCount:1}}if(sql.startsWith('insert into audit_logs'))return {rows:[],rowCount:1};throw new Error(`Consulta inesperada: ${sql}`)});const app=await maintenanceApp(pool);const res=await invoke(app.route('patch','/api/fleet/maintenance/:id'),{params:{id:'8'},body:{notes:'corregida',parts_cost_clp:0,labor_cost_clp:0}});assert.equal(res.statusCode,200);assert.equal(updateValues[4],185000);assert.equal(pool.releases,1);
});

test('GET aplica filtros, company scope y orden determinista para historial',async()=>{
 const pool=mockPool(async(sql,values)=>{assert.match(sql,/m\.company_id=\$1 and m\.truck_id=\$2/);assert.match(sql,/q\.status=\$3 and q\.maintenance_type=\$4/);assert.match(sql,/q\.effective_date >= \$5 and q\.effective_date <= \$6/);assert.match(sql,/q\.is_upcoming=true/);assert.match(sql,/q\.is_overdue=true/);assert.match(sql,/order by q\.effective_date desc nulls last,q\.id desc limit 1000/);assert.deepEqual(values,[10,3,'Pendiente','Preventiva','2026-08-01','2026-08-31']);return {rows:[],rowCount:0}});const app=await maintenanceApp(pool);const res=await invoke(app.route('get','/api/fleet/maintenance'),{query:{truck_id:'3',status:'Pendiente',maintenance_type:'Preventiva',from:'2026-08-01',to:'2026-08-31',upcoming:'true',overdue:'true'}});assert.equal(res.statusCode,200);assert.deepEqual(res.payload,[]);
});

test('GET calcula costo por km solo con odómetros consecutivos válidos y conserva legacy',async()=>{
 const rows=[{id:3,truck_id:3,truck_patente:'ABCD12',odometer_km:'11000',previous_odometer_km:'10500',cost_clp:'100000',is_upcoming:false,is_overdue:false},{id:2,truck_id:3,truck_patente:'ABCD12',odometer_km:'10500',previous_odometer_km:null,cost_clp:'70000',is_upcoming:true,is_overdue:false},{id:1,truck_id:null,truck:'Texto legacy',odometer_km:'12000',previous_odometer_km:null,cost_clp:'50000',is_upcoming:false,is_overdue:true}];
 const pool=mockPool(async()=>({rows,rowCount:3}));const app=await maintenanceApp(pool);const res=await invoke(app.route('get','/api/fleet/maintenance'),{query:{include_summary:'true'}});assert.equal(res.payload.records[0].distance_since_previous_km,500);assert.equal(res.payload.records[0].cost_per_km,200);assert.equal(res.payload.records[1].cost_per_km,null);assert.equal(res.payload.records[2].truck_id,null);assert.equal(res.payload.records[2].cost_per_km,null);assert.deepEqual(res.payload.totals,{maintenance_count:3,total_cost_clp:220000,upcoming_count:1,overdue_count:1});assert.equal(res.payload.summary.length,1);assert.deepEqual(res.payload.summary[0],{truck_id:3,patente:'ABCD12',maintenance_count:2,total_cost_clp:170000,upcoming_count:1,overdue_count:0});
});

test('GET no calcula costo por km cuando la distancia es cero o negativa',async()=>{
 const rows=[{id:2,truck_id:3,odometer_km:'10000',previous_odometer_km:'10000',cost_clp:'100000'},{id:1,truck_id:3,odometer_km:'9000',previous_odometer_km:'10000',cost_clp:'100000'}];const pool=mockPool(async()=>({rows,rowCount:2}));const app=await maintenanceApp(pool);const res=await invoke(app.route('get','/api/fleet/maintenance'),{query:{include_summary:'true'}});for(const row of res.payload.records){assert.equal(row.distance_since_previous_km,null);assert.equal(row.cost_per_km,null)}
});
