const test=require('node:test');
const assert=require('node:assert/strict');
const {registerOperationsRoutes}=require('../operations-api');
function app(){const routes=[];for(const method of ['get','post','patch'])routes[method]=(path,...handlers)=>routes.push({method,path,handlers});routes.route=(method,path)=>routes.find(r=>r.method===method&&r.path===path);return routes}
function response(){return {statusCode:200,payload:undefined,status(code){this.statusCode=code;return this},json(value){this.payload=value;return this},sendStatus(code){this.statusCode=code;return this}}}
async function invoke(route,user,body={},params={id:'7'}){const req={user,body,params,query:{},ip:'127.0.0.1'};const res=response();let i=0;const next=async()=>{const h=route.handlers[i++];if(h)return h(req,res,next)};await next();return res}
function pool(resolver){const calls=[];const client={async query(sql,values=[]){calls.push({sql,values});return resolver(sql,values)},release(){}};return {calls,async connect(){return client},async query(sql,values=[]){calls.push({sql,values});return resolver(sql,values)}}}
const modern=(company,permissions=['trips.manage'],extra={})=>({id:7,actor_type:'company',scope:'company',company_id:company,membership_id:11,platform_membership_id:null,role_code:'operations',permissions,...extra});
const platform={id:1,actor_type:'platform',scope:'platform',company_id:null,membership_id:null,platform_membership_id:4,role_code:'platform_superadmin',permissions:['trips.manage']};
const unresolved={id:2,actor_type:'unresolved',scope:null,company_id:null,membership_id:null,platform_membership_id:null,role_code:null,permissions:['trips.manage']};
const legacy={id:3,actor_type:'legacy',scope:'company',company_id:10,membership_id:null,platform_membership_id:null,role_code:'admin',permissions:[]};
const trip={id:7,company_id:10,driver_id:3,truck_id:4};
function eventPool(expectedCompany){return pool(async(sql,values)=>{if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return {rows:[]};if(sql.toLowerCase().includes('from trips')){if(values.length>1)assert.equal(values[1],expectedCompany);return {rowCount:1,rows:[trip]}}if(sql.startsWith('insert into trip_events'))return {rowCount:1,rows:[{id:9}]};if(sql.startsWith('insert into audit_logs'))return {rowCount:1,rows:[]};throw Error(sql)})}

test('operations usa membership A aunque users.company_id legacy sea B',async()=>{const p=eventPool(10),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('post','/api/operations/trips/:id/events'),modern(10,['trips.manage'],{legacy_company_id:20}),{event_type:'Carga'});assert.equal(r.statusCode,201);assert.deepEqual(p.calls.find(x=>x.sql.includes('from trips t where t.id=$1')).values,['7',10])});
test('operations funciona con membership A aunque company_id legacy sea null',async()=>{const p=eventPool(10),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('post','/api/operations/trips/:id/events'),modern(10,['trips.manage'],{legacy_company_id:null}),{event_type:'Carga'});assert.equal(r.statusCode,201)});
test('operations no selecciona una empresa con memberships múltiples',async()=>{const p=pool(async(sql,values)=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[]};if(sql.includes('from trips t where t.id=$1')){assert.deepEqual(values,['7',null]);return {rowCount:0,rows:[]}}throw Error(sql)}),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('post','/api/operations/trips/:id/events'),unresolved,{event_type:'Carga'});assert.equal(r.statusCode,404)});
test('platform sin contexto no opera sobre un trip',async()=>{const p=pool(async(sql,values)=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[]};if(sql.includes('from trips t where t.id=$1')){assert.deepEqual(values,['7',null]);return {rowCount:0,rows:[]}}throw Error(sql)}),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('post','/api/operations/trips/:id/events'),platform,{event_type:'Carga'});assert.equal(r.statusCode,404)});
test('company moderno ignora body.company_id malicioso',async()=>{const p=eventPool(10),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('post','/api/operations/trips/:id/events'),modern(10),{event_type:'Carga',company_id:20});assert.equal(r.statusCode,201);assert.deepEqual(p.calls.find(x=>x.sql.includes('from trips t where t.id=$1')).values,['7',10])});
test('trip de B no es accesible por ID desde actor A',async()=>{const p=pool(async(sql,values)=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[]};if(sql.includes('from trips t where t.id=$1')){assert.deepEqual(values,['7',10]);return {rowCount:0,rows:[]}}throw Error(sql)}),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('post','/api/operations/trips/:id/events'),modern(10),{event_type:'Carga'});assert.equal(r.statusCode,404);assert.equal(p.calls.some(x=>x.sql.startsWith('insert into trip_events')),false)});
test('admin moderno no activa bypass global',async()=>{const p=pool(async(sql,values)=>{if(sql==='BEGIN'||sql==='ROLLBACK')return {rows:[]};if(sql.includes('from trips t where t.id=$1')){assert.deepEqual(values,['7',10]);return {rowCount:0,rows:[]}}throw Error(sql)}),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('post','/api/operations/trips/:id/events'),modern(10,['trips.manage'],{role_code:'admin'}),{event_type:'Carga',company_id:20});assert.ok([400,404].includes(r.statusCode))});
test('legacy admin conserva bypass histórico',async()=>{const p=pool(async(sql,values)=>{if(sql.toLowerCase().includes('from trucks')||sql.toLowerCase().includes('from drivers')||sql.toLowerCase().includes('from clients')||sql.toLowerCase().includes('from routes')){assert.deepEqual(values,[]);return {rowCount:0,rows:[]}}throw Error(sql)}),a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('get','/api/operations/options'),legacy);assert.equal(r.statusCode,200)});

test('driverAccess permanece intacto y bloquea driver sin asociación',async()=>{const p={async query(){throw Error('No debe consultar')},async connect(){throw Error('No debe conectar')}};const a=app();await registerOperationsRoutes(a,p);const r=await invoke(a.route('get','/api/driver/trips'),{id:8,role_code:'driver',company_id:10,driver_id:null,permissions:[]});assert.equal(r.statusCode,403)});
