const test=require('node:test');
const assert=require('node:assert/strict');
const {createStorage,storageConfig,objectKey,StorageConfigError,StorageOperationError}=require('../storage');
function fake(){const calls=[];return {calls,async send(command){calls.push(command);if(this.fail)throw Error('S3 unavailable');return {Body:Buffer.from('data')}}}}
const env={S3_REGION:'eu-west-1',S3_BUCKET:'private-evidence',S3_ENDPOINT:'https://objects.example.test',S3_ACCESS_KEY_ID:'access',S3_SECRET_ACCESS_KEY:'secret'};
test('storage exige configuración S3 completa',()=>{assert.deepEqual(storageConfig(env),{region:'eu-west-1',bucket:'private-evidence',endpoint:'https://objects.example.test',accessKeyId:'access',secretAccessKey:'secret',forcePathStyle:false});assert.throws(()=>storageConfig({...env,S3_BUCKET:''}),StorageConfigError)});
test('object keys son internos, aislados y no usan nombres de archivo',()=>{const key=objectKey({companyId:10,proofId:22,type:'signature',id:'123e4567-e89b-12d3-a456-426614174000'});assert.equal(key,'companies/10/proofs/22/signature/123e4567-e89b-12d3-a456-426614174000');assert.throws(()=>objectKey({companyId:10,proofId:22,type:'photo',id:'../../file'}))});
test('put, get y delete delegan al cliente S3',async()=>{const client=fake(),storage=createStorage({env,client}),key=objectKey({companyId:10,proofId:22,type:'photo',id:'123e4567-e89b-12d3-a456-426614174000'});assert.deepEqual(await storage.put({key,body:Buffer.from('x'),mimeType:'image/png',size:1}),{key});assert.ok((await storage.get(key)).Body);assert.deepEqual(await storage.delete(key),{key});assert.equal(client.calls.length,3);assert.equal(client.calls[0].input.Bucket,'private-evidence');assert.equal(client.calls[0].input.Key,key)});
test('storage controla errores de S3 sin ocultarlos',async()=>{const client=fake();client.fail=true;const storage=createStorage({env,client});await assert.rejects(()=>storage.put({key:'safe/key',body:Buffer.from('x')}),e=>e instanceof StorageOperationError&&e.operation==='put');await assert.rejects(()=>storage.get('safe/key'),e=>e instanceof StorageOperationError&&e.operation==='get');await assert.rejects(()=>storage.delete('safe/key'),e=>e instanceof StorageOperationError&&e.operation==='delete')});
